

; pitch
	const_def
	const __
	const C_
	const C#
	const D_
	const D#
	const E_
	const F_
	const F#
	const G_
	const G#
	const A_
	const A#
	const B_
	const CC ; used for pitchoffset

; channel
	const_def
	const CHAN1
	const CHAN2
	const CHAN3
	const CHAN4
DEF NUM_MUSIC_CHANS EQU const_value
DEF NUM_NOISE_CHANS EQU const_value
	const CHAN5
	const CHAN6
	const CHAN7
	const CHAN8
DEF NUM_CHANNELS EQU const_value

; Flags1
DEF SOUND_CHANNEL_ON EQU 0
DEF SOUND_SUBROUTINE EQU 1
DEF SOUND_LOOPING EQU 2
DEF SOUND_SFX EQU 3
DEF SOUND_NOISE EQU 4
DEF SOUND_REST EQU 5

; Flags2
DEF SOUND_VIBRATO EQU 0
DEF SOUND_PITCH_WHEEL EQU 1
DEF SOUND_DUTY EQU 2
DEF SOUND_UNKN_0B EQU 3
DEF SOUND_CRY_PITCH EQU 4
DEF SOUND_UNKN_0D EQU 5
DEF SOUND_UNKN_0E EQU 6
DEF SOUND_UNKN_0F EQU 7

; Flags3
DEF SOUND_VIBRATO_DIR EQU 0
DEF SOUND_PITCH_WHEEL_DIR EQU 1

; NoteFlags
DEF NOTE_DUTY_OVERRIDE EQU 0
DEF NOTE_FREQ_OVERRIDE EQU 1
DEF NOTE_UNKN_3 EQU 3
DEF NOTE_NOISE_SAMPLING EQU 4
DEF NOTE_REST EQU 5
DEF NOTE_VIBRATO_OVERRIDE EQU 6
