	const_def

	const ENGINE_RADIO_CARD ; $0
	const ENGINE_MAP_CARD
	const ENGINE_PHONE_CARD
	const ENGINE_EXPN_CARD
	const ENGINE_TRAINER_CARD

	const ENGINE_DAYCARE_MAN_HAS_EGG
	const ENGINE_DAYCARE_MAN_HAS_MON
	const ENGINE_DAYCARE_LADY_HAS_MON

	const ENGINE_MOM_SAVING_MONEY ; $8
	const ENGINE_DST

	const ENGINE_POKEDEX
	const ENGINE_UNOWN_DEX
	const ENGINE_POKERUS
	const ENGINE_ROCKET_SIGNAL_ON_CH20
	const ENGINE_CREDITS_SKIP
	const ENGINE_BUG_CONTEST_ON
	const ENGINE_ROCKETS_IN_RADIO_TOWER ; $10
	const ENGINE_SAFARI_GAME
	const ENGINE_BUG_CONTEST_TIMER
	const ENGINE_SEEN_SHAMOUTI_ISLAND
	const ENGINE_BIKE_SHOP_CALL_ENABLED
	const ENGINE_GIVE_POKERUS
	const ENGINE_EXORCISED_LAV_RADIO_TOWER
	const ENGINE_ROCKETS_IN_MAHOGANY

	const ENGINE_STRENGTH_ACTIVE ; $18
	const ENGINE_ALWAYS_ON_BIKE
	const ENGINE_DOWNHILL
	const ENGINE_AUTOSURF_ACTIVE
	const ENGINE_ROCK_SMASH_ACTIVE
	const ENGINE_HEADBUTT_ACTIVE
	const ENGINE_AUTOWHIRLPOOL_ACTIVE
	const ENGINE_AUTOWATERFALL_ACTIVE
	const ENGINE_AUTOCUT_ACTIVE ; $20
	const ENGINE_ROCK_CLIMB_ACTIVE

	const ENGINE_BIKE_GEAR
	
	const ENGINE_HAVE_FOLLOWER
	
	const ENGINE_ENCOUNTER_HOUSE
	
	const ENGINE_FIRSTBADGE
	const ENGINE_SECONDBADGE
	const ENGINE_THIRDBADGE
	const ENGINE_FOURTHBADGE
	const ENGINE_FIFTHBADGE
	const ENGINE_SIXTHBADGE
	const ENGINE_SEVENTHBADGE
	const ENGINE_EIGHTHBADGE ; $28

	const ENGINE_UNLOCKED_UNOWNS_1
	const ENGINE_UNLOCKED_UNOWNS_2
	const ENGINE_UNLOCKED_UNOWNS_3
	const ENGINE_UNLOCKED_UNOWNS_4
	const ENGINE_UNLOCKED_UNOWNS_5
	const ENGINE_UNLOCKED_UNOWNS_6
	const ENGINE_UNLOCKED_UNOWNS_7
	const ENGINE_UNLOCKED_UNOWNS_8 ; $38

	const ENGINE_FLYPOINT_HOME
	const ENGINE_FLYPOINT_SUNSET
	const ENGINE_FLYPOINT_DAYBREAK
	const ENGINE_FLYPOINT_GLINT
	const ENGINE_FLYPOINT_STARGLOW
	const ENGINE_FLYPOINT_LAKE_ONWA
	const ENGINE_FLYPOINT_SUNBEAM
	const ENGINE_FLYPOINT_EVENTIDE
	const ENGINE_FLYPOINT_FLICKER ; $40
	const ENGINE_FLYPOINT_TWINKLE
	const ENGINE_FLYPOINT_LUSTER
	const ENGINE_FLYPOINT_SHIMMER
	const ENGINE_FLYPOINT_BRILLO
	const ENGINE_FLYPOINT_UNUSED9
	const ENGINE_FLYPOINT_UNUSED10
	const ENGINE_FLYPOINT_UNUSED11
	const ENGINE_FLYPOINT_UNUSED12 ; $48
	const ENGINE_FLYPOINT_UNUSED13
	const ENGINE_FLYPOINT_UNUSED14
	const ENGINE_FLYPOINT_UNUSED15
	const ENGINE_FLYPOINT_UNUSED16
	const ENGINE_FLYPOINT_UNUSED17
	const ENGINE_FLYPOINT_UNUSED18
	const ENGINE_FLYPOINT_UNUSED19
	const ENGINE_FLYPOINT_UNUSED20 ; $50
	const ENGINE_FLYPOINT_UNUSED21
	const ENGINE_FLYPOINT_UNUSED22

	const ENGINE_LUCKY_NUMBER_SHOW

	const ENGINE_DAILY_BIKINI_CONTEST
	const ENGINE_DAILY_BUG_CONTEST
	const ENGINE_SPECIAL_WILDDATA
	const ENGINE_DAILY_ROUTE_GARDEN ; $58
	const ENGINE_ALL_FRUIT_TREES
	const ENGINE_DONE_RANCH_RACE_TODAY
	const ENGINE_GOLDENROD_UNDERGROUND_MERCHANT_CLOSED
	const ENGINE_STREETLIGHTS

	const ENGINE_GYM_LEADER_REMATCH_1
	const ENGINE_GYM_LEADER_REMATCH_2
	const ENGINE_GYM_LEADER_REMATCH_3
	const ENGINE_DAILY_PHOTOGRAPH ; $60
	const ENGINE_DAILY_SHRINE_VISIT
	const ENGINE_DAILY_MYSTERY_GIFT
	const ENGINE_RED_IN_MOUNT_SILVER
	const ENGINE_LEAF_IN_NAVEL_ROCK

	const ENGINE_BOUGHT_LEFTOVERS
	const ENGINE_TOOK_HYPER_TEST
	const ENGINE_CHERYL_DONE_TODAY
	const ENGINE_RILEY_DONE_TODAY ; $68
	const ENGINE_BUCK_DONE_TODAY
	const ENGINE_MARLEY_DONE_TODAY
	const ENGINE_MIRA_DONE_TODAY
	const ENGINE_ANABEL_DONE_TODAY

	const ENGINE_MT_MOON_SQUARE_CLEFAIRY
	const ENGINE_UNION_CAVE_LAPRAS
	const ENGINE_GOLDENROD_UNDERGROUND_GOT_HAIRCUT
	const ENGINE_GOLDENROD_MALL_5F_HAPPINESS_EVENT ; $78
	const ENGINE_TEA_IN_BLUES_HOUSE
	const ENGINE_INDIGO_PLATEAU_RIVAL_FIGHT
	const ENGINE_INDIGO_PLATEAU_LYRA_FIGHT
	const ENGINE_BUENAS_PASSWORD
	
	const ENGINE_GLINT_GROVE_PILE_1
	const ENGINE_GLINT_GROVE_PILE_2
	const ENGINE_GLINT_GROVE_PILE_3
	const ENGINE_GLINT_GROVE_PILE_4 ; $70
	const ENGINE_GLINT_GROVE_PILE_5
	const ENGINE_GLINT_GROVE_PILE_6
	const ENGINE_GLINT_GROVE_PILE_7
	const ENGINE_GLINT_GROVE_PILE_UNUSED

	const ENGINE_BUENAS_PASSWORD_2
	const ENGINE_GOLDENROD_DEPT_STORE_SALE_IS_ON

	const ENGINE_GAME_TIMER_PAUSE

	const ENGINE_HAVE_EXAMINED_GS_BALL
	const ENGINE_HAVE_SILPHSCOPE2
	const ENGINE_HAVE_SHINY_CHARM

	const ENGINE_JACK
	const ENGINE_HUEY
	const ENGINE_GAVEN
	const ENGINE_BETH
	const ENGINE_JOSE ; $88
	const ENGINE_REENA
	const ENGINE_JOEY
	const ENGINE_WADE
	const ENGINE_RALPH
	const ENGINE_LIZ
	const ENGINE_ANTHONY
	const ENGINE_TODD
	const ENGINE_GINA ; $90
	const ENGINE_ARNIE
	const ENGINE_ALAN
	const ENGINE_DANA
	const ENGINE_CHAD
	const ENGINE_TULLY
	const ENGINE_BRENT
	const ENGINE_TIFFANY
	const ENGINE_VANCE ; $98
	const ENGINE_WILTON
	const ENGINE_PARRY
	const ENGINE_ERIN

	const ENGINE_BEVERLY_HAS_NUGGET
	const ENGINE_JOSE_HAS_STAR_PIECE
	const ENGINE_WADE_HAS_ITEM
	const ENGINE_GINA_HAS_LEAF_STONE
	const ENGINE_ALAN_HAS_FIRE_STONE ; $a0
	const ENGINE_DANA_HAS_THUNDERSTONE
	const ENGINE_DEREK_HAS_NUGGET
	const ENGINE_TULLY_HAS_WATER_STONE
	const ENGINE_TIFFANY_HAS_PINK_BOW
	const ENGINE_WILTON_HAS_ITEM

	const ENGINE_JACK_MONDAY_MORNING
	const ENGINE_HUEY_WEDNESDAY_NIGHT
	const ENGINE_GAVEN_THURSDAY_MORNING ; $a8
	const ENGINE_BETH_FRIDAY_AFTERNOON
	const ENGINE_JOSE_SATURDAY_NIGHT
	const ENGINE_REENA_SUNDAY_MORNING
	const ENGINE_JOEY_MONDAY_AFTERNOON
	const ENGINE_WADE_TUESDAY_NIGHT
	const ENGINE_RALPH_WEDNESDAY_MORNING
	const ENGINE_LIZ_THURSDAY_AFTERNOON
	const ENGINE_ANTHONY_FRIDAY_NIGHT ; $b0
	const ENGINE_TODD_SATURDAY_MORNING
	const ENGINE_GINA_SUNDAY_AFTERNOON
	const ENGINE_ARNIE_TUESDAY_MORNING
	const ENGINE_ALAN_WEDNESDAY_AFTERNOON
	const ENGINE_DANA_THURSDAY_NIGHT
	const ENGINE_CHAD_FRIDAY_MORNING
	const ENGINE_TULLY_SUNDAY_NIGHT
	const ENGINE_BRENT_MONDAY_MORNING ; $b8
	const ENGINE_TIFFANY_TUESDAY_AFTERNOON
	const ENGINE_VANCE_WEDNESDAY_NIGHT
	const ENGINE_WILTON_THRUSDAY_MORNING
	const ENGINE_PARRY_FRIDAY_AFTERNOON
	const ENGINE_ERIN_SATURDAY_NIGHT

	const ENGINE_KRIS_IN_CABLE_CLUB

	const ENGINE_DUNSPARCE_SWARM
	const ENGINE_YANMA_SWARM ; $c0
	
	const ENGINE_GOT_ROCK_SMASH
	const ENGINE_GOT_CUT
	const ENGINE_GOT_FLY
	const ENGINE_GOT_ROCK_CLIMB
	const ENGINE_GOT_SURF

;old and unused
	const ENGINE_MET_STANLEY
	const ENGINE_MET_RODNEY
	const ENGINE_MET_WENDY
	const ENGINE_MET_CHARLIE
	const ENGINE_READ_CHUCK_JOURNAL
	const ENGINE_READ_JASMINE_JOURNAL
	const ENGINE_READ_PRYCE_JOURNAL
	const ENGINE_READ_CLAIR_JOURNAL ; $c8
	
	const ENGINE_PUNKS_IN_STARGLOW
	const ENGINE_PUNKS_ON_SUNBEAM
	const ENGINE_PUNKS_ON_TRAIN
	
	const ENGINE_NEAR_CAMPFIRE

NUM_ENGINE_FLAGS EQU const_value
