DEF LEN_2BPP_TILE EQU 16
DEF LEN_1BPP_TILE EQU 8
DEF TILES_PER_FRAME EQU 7
DEF TILESIZE EQU $10
DEF TILE_WIDTH EQU 8

DEF SCREEN_WIDTH EQU 20
DEF SCREEN_HEIGHT EQU 18
DEF SCREEN_WIDTH_PX EQU SCREEN_WIDTH * 8
DEF SCREEN_HEIGHT_PX EQU SCREEN_HEIGHT * 8

DEF BG_MAP_WIDTH  EQU 32
DEF BG_MAP_HEIGHT EQU 32
DEF WMISC_WIDTH   EQU 6 * 4
DEF WMISC_HEIGHT  EQU 5 * 4

DEF HP_BAR_LENGTH EQU 6
DEF HP_BAR_LENGTH_PX EQU HP_BAR_LENGTH * 8
DEF EXP_BAR_LENGTH EQU 8
DEF EXP_BAR_LENGTH_PX EQU EXP_BAR_LENGTH * 8

; popup map name signs
DEF POPUP_MAP_NAME_START  EQU $e0
DEF POPUP_MAP_NAME_SIZE   EQU 18
DEF POPUP_MAP_FRAME_START EQU $f3
DEF POPUP_MAP_FRAME_SIZE  EQU 8
DEF POPUP_MAP_FRAME_SPACE EQU $fb
DEF POPUP_MAP_FRAME_TOP	  EQU $f5

; hp palette
DEF HP_GREEN  EQU 0
DEF HP_YELLOW EQU 1
DEF HP_RED    EQU 2

; sprite_oam_struct members (see macros/wram.asm)
	const_def
	const SPRITEOAMSTRUCT_YCOORD     ; 0
	const SPRITEOAMSTRUCT_XCOORD     ; 1
	const SPRITEOAMSTRUCT_TILE_ID    ; 2
	const SPRITEOAMSTRUCT_ATTRIBUTES ; 3
DEF SPRITEOAMSTRUCT_LENGTH EQU const_value
DEF NUM_SPRITE_OAM_STRUCTS EQU 40 ; see wVirtualOAM

	const_def
	const ANIM_MON_SLOW    ; 0
	const ANIM_MON_NORMAL  ; 1
	const ANIM_MON_MENU    ; 2
	const ANIM_MON_TRADE   ; 3
	const ANIM_MON_EVOLVE  ; 4
	const ANIM_MON_HATCH   ; 5
	const ANIM_MON_UNUSED  ; 6
	const ANIM_MON_EGG1    ; 7
	const ANIM_MON_EGG2    ; 8
