	const_def
	const NORTH_ONWA_REGION
	const SOUTH_ONWA_REGION
	const ORANGE_REGION


	const_def

	const SPECIAL_MAP		 ; 00

	const SUNSET_BAY
	const SUNSET_CAPE
	const ROUTE_1
	const DAYBREAK_VILLAGE
	const ROUTE_2
	const MT_ONWA
	const GLINT_CITY
	const GLINT_GROVE
	const ROUTE_3
	const STARGLOW_CAVERN
	const STARGLOW_VALLEY
	const ROUTE_4
	const HUNTERS_THICKET
	const ROUTE_5
	const ROUTE_6
	const ROUTE_7
	const LAKE_ONWA
	const SUNBEAM_ISLAND
	const SUNBEAM_JUNGLE
	const ROUTE_8
	const EVENTIDE_FOREST
	const EVENTIDE_VILLAGE
	const ROUTE_9
	const ROUTE_11
	const DODRIO_RANCH
	const FLICKER_STATION
	const FLICKER_PASS
	const ROUTE_10
	const TWINKLE_TOWN
	const ICICLE_CAVERN
	const LUSTER_CITY
	const LUSTER_SEWERS
	const ROUTE_12
	const SKATEPARK
	const AIRPORT
	const ROUTE_13
	const ROUTE_14
	const ROUTE_15
	const ROUTE_16
	const OLD_MANOR
	const FROZEN_RUINS
	const LUSTER_STATION
	const RESIDENTIAL_DISTRICT
	const SHOPPING_DISTRICT
	const BUSINESS_DISTRICT
	const FAKE_SUNSET_BAY
	const FAKE_SUNSET_CAPE
	const FAKE_ROUTE_1
	const STARGLOW_DEPTHS
	const UNKNOWN_PASSAGE
	const CONNECTING_CAVERN

DEF SOUTH_ONWA_LANDMARK EQU const_value

	const SHIMMER_CITY
	const ROUTE_19
	const SEASIDE_CAVE
	const ROUTE_20
	const RADIANT_TOWNSHIP
	const ROUTE_21
	const DUSK_TURNPIKE
	const ROUTE_22
	const CROSSROADS
	const ROUTE_23
	const KOMORE_VILLAGE
	const ROUTE_24
	const ROUTE_25
	const ROUTE_26
	const ROUTE_27
	const BRIGHTBURG
	const ROUTE_28
	const GREEN_GROTTO
	const ROUTE_29
	const OBSCURA_CITY
	const ROUTE_30
	const ROUTE_31
	const ROUTE_32
	const ROUTE_11_SOUTH
	const BONE_CAVERN
	const LUMINA_TOWN
	const AUREOLE_TOWN
	
	const BRILLO_TOWN
	const ROUTE_17
	const ROUTE_18
	const DESERT_WASTELAND

DEF SHAMOUTI_LANDMARK EQU const_value

	const GATE_LANDMARK
	const DIVE_LANDMARK
	const FARAWAY_ISLAND

DEF NUM_LANDMARKS EQU const_value
