; Boolean checks
DEF FALSE EQU 0
DEF TRUE  EQU 1

; flag manipulation
DEF RESET_FLAG EQU 0
DEF SET_FLAG   EQU 1
DEF CHECK_FLAG EQU 2

DEF SAVE_CHECK_VALUE_1 EQU 99
DEF SAVE_CHECK_VALUE_2 EQU 127

DEF HMENURETURN_SCRIPT EQU %10000000
DEF HMENURETURN_ASM    EQU %11111111

DEF MORN_HOUR EQU 5
DEF DAY_HOUR EQU 10
DEF DUSK_HOUR EQU 19
DEF NITE_HOUR EQU 20

if DEF(NO_RTC)
DEF NO_RTC_SPEEDUP EQU 6
endc

; mail
DEF MAIL_STRUCT_LENGTH EQU $2f
DEF MAILBOX_CAPACITY   EQU 10
DEF MAIL_MSG_LENGTH    EQU $20

DEF SHINY_NUMERATOR         EQU 16 ; 16/65536 = 1/4096
DEF CHARMED_SHINY_NUMERATOR EQU 48 ; 48/65536 = 3/4096

; playergender values
DEF CORY   EQU 0
DEF CORA   EQU 1
DEF PIPPI  EQU 2
DEF RED    EQU 3
DEF LEAF   EQU 4
DEF GOLD   EQU 5
DEF KRIS   EQU 6

DEF MINA_MON_ROUTE_6 			EQU 101
DEF MINA_MON_ROUTE_11 			EQU 102
DEF MINA_MON_RADIANT_FIELD		EQU 103
DEF MINA_MON_ROUTE_29 			EQU 104
DEF MINA_MON_ROUTE_10 			EQU 105


DEF NUM_LOST_GIRLS EQU 7
	
	const_def 1
	const SKATEPARK_RAIL_1
	const SKATEPARK_RAIL_2
	const SKATEPARK_RAIL_3
	const SKATEPARK_RAIL_4
	const SKATEPARK_RAIL_5
	const SKATEPARK_FLOWERBED_1
	const SKATEPARK_FLOWERBED_2
	const SKATEPARK_FLOWERBED_3
	const SKATEPARK_FLOWERBED_4
	const SKATEPARK_FLOWERBED_5
	const SKATEPARK_FLOWERBED_6
	const SKATEPARK_FLOWERBED_7
	const SKATEPARK_FOUNTAIN

	const_def 1
	const TREEMONS_GLINT
	const TREEMONS_GROVE
	const TREEMONS_STARGLOW
	const TREEMONS_MOUNTAINTOP
	const TREEMONS_SUNBEAM
	const TREEMONS_EVENTIDE
	const TREEMONS_TWINKLE
	const TREEMONS_LUSTER
	const TREEMONS_SHIMMER
	const TREEMONS_OASIS
	const TREEMONS_RADIANT
	const TREEMONS_KOMORE
	const TREEMONS_BRIGHT
	const TREEMONS_ROCK
	const TREEMONS_PETAL
DEF NUM_TREEMON_MAPS EQU const_value

; PredefPals indexes (see gfx/sgb/predef.pal)
; GetPredefPal arguments (see engine/gfx/color.asm)
	const_def
	const PREDEFPAL_ROUTES
	const PREDEFPAL_PALLET
	const PREDEFPAL_VIRIDIAN
	const PREDEFPAL_PEWTER
	const PREDEFPAL_CERULEAN
	const PREDEFPAL_LAVENDER
	const PREDEFPAL_VERMILION
	const PREDEFPAL_CELADON
	const PREDEFPAL_FUCHSIA
	const PREDEFPAL_CINNABAR
	const PREDEFPAL_SAFFRON
	const PREDEFPAL_INDIGO
	const PREDEFPAL_NEW_BARK
	const PREDEFPAL_CHERRYGROVE
	const PREDEFPAL_VIOLET
	const PREDEFPAL_AZALEA
	const PREDEFPAL_GOLDENROD
	const PREDEFPAL_ECRUTEAK
	const PREDEFPAL_OLIVINE
	const PREDEFPAL_CIANWOOD
	const PREDEFPAL_MAHOGANY
	const PREDEFPAL_BLACKTHORN
	const PREDEFPAL_LAKE_OF_RAGE
	const PREDEFPAL_SILVER_CAVE
	const PREDEFPAL_DUNGEONS
	const PREDEFPAL_NITE
	const PREDEFPAL_BLACKOUT
	const PREDEFPAL_DIPLOMA ; RB_MEWMON
	const PREDEFPAL_TRADE_TUBE ; RB_BLUEMON
	const PREDEFPAL_POKEDEX ; RB_REDMON
	const PREDEFPAL_RB_CYANMON
	const PREDEFPAL_RB_PURPLEMON
	const PREDEFPAL_RB_BROWNMON
	const PREDEFPAL_RB_GREENMON
	const PREDEFPAL_RB_PINKMON
	const PREDEFPAL_RB_YELLOWMON
	const PREDEFPAL_CGB_BADGE ; RB_GRAYMON
	const PREDEFPAL_BETA_SHINY_MEWMON
	const PREDEFPAL_BETA_SHINY_BLUEMON
	const PREDEFPAL_BETA_SHINY_REDMON
	const PREDEFPAL_BETA_SHINY_CYANMON
	const PREDEFPAL_BETA_SHINY_PURPLEMON
	const PREDEFPAL_BETA_SHINY_BROWNMON
	const PREDEFPAL_BETA_SHINY_GREENMON
	const PREDEFPAL_BETA_SHINY_PINKMON
	const PREDEFPAL_BETA_SHINY_YELLOWMON
	const PREDEFPAL_PARTY_ICON ; BETA_SHINY_GRAYMON
	const PREDEFPAL_HP_GREEN
	const PREDEFPAL_HP_YELLOW
	const PREDEFPAL_HP_RED
	const PREDEFPAL_POKEGEAR
	const PREDEFPAL_BETA_LOGO_1
	const PREDEFPAL_BETA_LOGO_2
	const PREDEFPAL_GS_INTRO_GAMEFREAK_LOGO
	const PREDEFPAL_GS_INTRO_SHELLDER_LAPRAS
	const PREDEFPAL_BETA_INTRO_LAPRAS
	const PREDEFPAL_GS_INTRO_JIGGLYPUFF_PIKACHU_BG
	const PREDEFPAL_GS_INTRO_JIGGLYPUFF_PIKACHU_OB
	const PREDEFPAL_GS_INTRO_STARTERS_TRANSITION
	const PREDEFPAL_BETA_INTRO_VENUSAUR
	const PREDEFPAL_PACK ; GS_INTRO_CHARIZARD
	const PREDEFPAL_SLOT_MACHINE_0
	const PREDEFPAL_SLOT_MACHINE_1
	const PREDEFPAL_SLOT_MACHINE_2
	const PREDEFPAL_SLOT_MACHINE_3
	const PREDEFPAL_BETA_POKER_0
	const PREDEFPAL_BETA_POKER_1
	const PREDEFPAL_BETA_POKER_2
	const PREDEFPAL_BETA_POKER_3
	const PREDEFPAL_BETA_RADIO
	const PREDEFPAL_BETA_POKEGEAR
	const PREDEFPAL_47
	const PREDEFPAL_GS_TITLE_SCREEN_0
	const PREDEFPAL_GS_TITLE_SCREEN_1
	const PREDEFPAL_GS_TITLE_SCREEN_2
	const PREDEFPAL_GS_TITLE_SCREEN_3
	const PREDEFPAL_UNOWN_PUZZLE
	const PREDEFPAL_GAMEFREAK_LOGO_OB
	const PREDEFPAL_GAMEFREAK_LOGO_BG
DEF NUM_PREDEF_PALS EQU const_value

; SGB system command codes
; http://gbdev.gg8.se/wiki/articles/SGB_Functions#SGB_System_Command_Table
	const_def
	const SGB_PAL01
	const SGB_PAL23
	const SGB_PAL03
	const SGB_PAL12
	const SGB_ATTR_BLK
	const SGB_ATTR_LIN
	const SGB_ATTR_DIV
	const SGB_ATTR_CHR
	const SGB_SOUND
	const SGB_SOU_TRN
	const SGB_PAL_SET
	const SGB_PAL_TRN
	const SGB_ATRC_EN
	const SGB_TEST_EN
	const SGB_ICON_EN
	const SGB_DATA_SND
	const SGB_DATA_TRN
	const SGB_MLT_REQ
	const SGB_JUMP
	const SGB_CHR_TRN
	const SGB_PCT_TRN
	const SGB_ATTR_TRN
	const SGB_ATTR_SET
	const SGB_MASK_EN
	const SGB_OBJ_TRN

DEF PALPACKET_LENGTH EQU $10

; movement
	const_def
	const STEP_SLOW
	const STEP_WALK
	const STEP_BIKE
	const STEP_RUN
	const STEP_LEDGE
	const STEP_ICE
	const STEP_TURN
	const STEP_BACK_LEDGE
	const STEP_WALK_IN_PLACE
	const STEP_SPIN
	const STEP_FAST ; same as STEP_RUN but without doubling animation speed
	const STEP_SURF
	const STEP_SLIDE
	const STEP_SKATEBOARD
	const STEP_SKATEBOARD_PUSH
	const STEP_SLOW_SLIDE

	const_def
	const STEP_TYPE_SLOW
	const STEP_TYPE_NORMAL
	const STEP_TYPE_SUPER_FAST
	const STEP_TYPE_FAST
	const STEP_TYPE_MEDIUM
	const STEP_TYPE_NONE

DEF const_value = 1
	const HAPPINESS_GAINLEVEL         ; 01
	const HAPPINESS_USEDITEM          ; 02
	const HAPPINESS_USEDXITEM         ; 03
	const HAPPINESS_GYMBATTLE         ; 04
	const HAPPINESS_LEARNMOVE         ; 05
	const HAPPINESS_FAINTED           ; 06
	const HAPPINESS_POISONFAINT       ; 07
	const HAPPINESS_BEATENBYSTRONGFOE ; 08
	const HAPPINESS_YOUNGCUT1         ; 09
	const HAPPINESS_YOUNGCUT2         ; 0a
	const HAPPINESS_YOUNGCUT3         ; 0b
	const HAPPINESS_OLDERCUT1         ; 0c
	const HAPPINESS_OLDERCUT2         ; 0d
	const HAPPINESS_OLDERCUT3         ; 0e
	const HAPPINESS_BITTERPOWDER      ; 0f
	const HAPPINESS_ENERGYROOT        ; 10
	const HAPPINESS_REVIVALHERB       ; 11
	const HAPPINESS_MASSAGE           ; 12
	const HAPPINESS_GAINLEVELATHOME   ; 13
	const HAPPINESS_PHOTOGRAPH        ; 14
	const HAPPINESS_BLESSING          ; 15
