	const_def
	const NO_MOVE      ; $00
	const ROCK_CLIMB   ; $01
	const KARATE_CHOP  ; $02
	const DOUBLE_SLAP  ; $03
	const BONE_CLUB    ; $04
	const DRAGON_CLAW  ; $05
	const PAY_DAY      ; $06
	const FIRE_PUNCH   ; $07
	const ICE_PUNCH    ; $08
	const THUNDERPUNCH ; $09
	const FLAME_CHARGE ; $0a
	const X_SCISSOR    ; $0b
	const SMOG	       ; $0c
	const AIR_SLASH    ; $0d
	const SWORDS_DANCE ; $0e
	const CUT          ; $0f
	const GUST         ; $10
	const WING_ATTACK  ; $11
	const SUCKER_PUNCH ; $12
	const FLY          ; $13
	const DAZZLINGLEAM ; $14
	const FLAIL  	   ; $15
	const VINE_WHIP    ; $16
	const STOMP        ; $17
	const HEX		   ; $18
	const FLARE_BLITZ  ; $19
	const STONE_EDGE   ; $1a
	const FOCUS_BLAST  ; $1b
	const BULLET_SEED  ; $1c
	const HEADBUTT     ; $1d
	const HORN_ATTACK  ; $1e
	const FIRE_FANG    ; $1f
	const ICE_FANG     ; $20
	const THUNDER_FANG ; $21
	const TACKLE_SCRATCH_POUND       			; $22
	const BODY_SLAM    ; $23
	const WRAP         ; $24
	const TAKE_DOWN    ; $25
	const THRASH       ; $26
	const DOUBLE_EDGE  ; $27
	const HAIL         ; $28
	const POISON_STING ; $29
	const PIN_MISSILE  ; $2a
	const LEER_TAIL_WHIP         				; $2b
	const BITE         ; $2c
	const GROWL        ; $2d
	const ROAR_WHIRLWIND        	 			; $2e
	const SING         ; $2f - COMBINE
	const SUPERSONIC   ; $30
	const SONIC_BOOM   ; $31
	const DISABLE      ; $32
	const ACID         ; $33
	const EMBER        ; $34
	const FLAMETHROWER ; $35
	const CALM_MIND    ; $36
	const WATER_GUN    ; $37
	const HYDRO_PUMP   ; $38
	const SURF         ; $39
	const ICE_BEAM     ; $3a
	const BLIZZARD     ; $3b
	const PSYBEAM      ; $3c
	const BUBBLE_BEAM  ; $3d
	const AURORA_BEAM  ; $3e
	const HYPER_BEAM   ; $3f
	const PECK         ; $40
	const DRILL_PECK   ; $41
	const SHADOW_BONE  ; $42
	const BONE_RUSH    ; $43
	const COUNTER      ; $44
	const SEISMIC_TOSS ; $45
	const STRENGTH     ; $46
	const ABSORB       ; $47
	const MEGA_DRAIN   ; $48
	const LEECH_SEED   ; $49
	const GROWTH       ; $4a - COMBINE
	const RAZOR_LEAF   ; $4b
	const SOLAR_BEAM   ; $4c
	const POISONPOWDER ; $4d
	const STUN_SPORE   ; $4e
	const SLEEP_POWDER ; $4f
	const PETAL_DANCE  ; $50
	const STRING_SHOT  ; $51
	const DRAGON_RAGE  ; $52
	const FIRE_SPIN    ; $53
	const THUNDERSHOCK ; $54
	const THUNDERBOLT  ; $55
	const THUNDER_WAVE ; $56
	const THUNDER      ; $57
	const ROCK_THROW   ; $58
	const EARTHQUAKE   ; $59
	const FAIRY_WIND   ; $5a
	const DIG          ; $5b
	const TOXIC        ; $5c
	const CONFUSION    ; $5d
	const PSYCHIC_M    ; $5e
	const HYPNOSIS     ; $5f - REMOVE
	const SIGNAL_BEAM  ; $60
	const AGILITY_ROCK_POLISH      ; $61
	const QUICK_ATTACK ; $62
	const RAGE         ; $63
	const TELEPORT     ; $64
	const NIGHT_SHADE  ; $65
	const DRAGON_PULSE ; $66
	const SCREECH      ; $67
	const DOUBLE_TEAM  ; $68
	const RECOVER      ; $69
	const ROCK_BLAST   ; $6a
	const MINIMIZE     ; $6b
	const SAND_ATTACK_SMOKESCREEN  				; $6c
	const CONFUSE_RAY  ; $6d
	const AQUA_TAIL    ; $6e
	const DEFENSE_CURL_HARDEN_WITHDRAW 			; $6f
	const BARRIER_IRON_DEFENSE_ACID_ARMOR      			; $70
	const LIGHT_SCREEN ; $71
	const HAZE         ; $72
	const REFLECT      ; $73
	const FOCUS_ENERGY ; $74
	const FLASH_CANNON ; $75
	const METRONOME    ; $76
	const SCALD        ; $77
	const SELFDESTRUCT ; $78
	const COTTON_GUARD ; $79
	const LICK         ; $7a
	const PSYSHOCK     ; $7b
	const VENOSHOCK    ; $7c
	const EARTH_POWER  ; $7d
	const FIRE_BLAST   ; $7e
	const WATERFALL    ; $7f
	const ICICLE_CRASH ; $80
	const SWIFT        ; $81
	const MIRROR_MOVE  ; $82
	const ICICLE_SPEAR ; $83
	const WORK_UP      ; $84
	const AMNESIA      ; $85
	const ROOST        ; $86
	const SOFTBOILED_MILK_DRINK   				; $87
	const HI_JUMP_KICK ; $88
	const GLARE        ; $89 - REMOVE
	const DREAM_EATER  ; $8a
	const POISON_JAB   ; $8b
	const BULLET_PUNCH ; $8c
	const LEECH_LIFE   ; $8d
	const DOUBLE_HIT   ; $8e
	const BRAVE_BIRD   ; $8f - REMOVE
	const TRANSFORM    ; $90
	const TOXIC_SPIKES ; $91
	const POISON_FANG  ; $92
	const SPORE        ; $93
	const FLASH        ; $94
	const LOCK_ON_MIND_READER	   				; $95
	const SPLASH       ; $96
	const DRAGON_DANCE ; $97
	const CRABHAMMER   ; $98
	const EXPLOSION    ; $99
	const FURY_SWIPES_FURY_ATTACK_COMET_PUNCH  	; $9a
	const BONEMERANG   ; $9b
	const REST         ; $9c
	const ROCK_SLIDE   ; $9d
	const SWEET_SCENT  ; $9e - REMOVE
	const BULK_UP      ; $9f
	const CONVERSION   ; $a0
	const TRI_ATTACK   ; $a1
	const SHARPEN_HOWL_MEDITATE	   				; $a2
	const SLASH        ; $a3
	const SUBSTITUTE   ; $a4
	const GIGA_IMPACT  ; $a5
	const SKETCH       ; $a6
	const DRAIN_PUNCH  ; $a7
	const ACROBATICS   ; $a8
	const WILL_O_WISP  ; $a9
	const ZEN_HEADBUTT ; $aa
	const VITAL_THROW  ; $ab
	const FLAME_WHEEL  ; $ac
	const HYPER_VOICE  ; $ad
	const CURSE        ; $ae
	const GYRO_BALL    ; $af
	const ENERGY_BALL  ; $b0
	const MIMIC		   ; $b1
	const NUZZLE       ; $b2
	const REVERSAL     ; $b3
	const SLUDGE       ; $b4
	const ICE_SHARD    ; $b5
	const PROTECT      ; $b6
	const MACH_PUNCH   ; $b7
	const SCARY_FACE_COTTON_SPORE   			; $b8
	const FEINT_ATTACK ; $b9
	const SWEET_KISS   ; $ba - REMOVE
	const BELLY_DRUM   ; $bb
	const SLUDGE_BOMB  ; $bc
	const MUD_SLAP     ; $bd
	const SHELL_SMASH  ; $be
	const SPIKES       ; $bf
	const ZAP_CANNON   ; $c0
	const FORESIGHT_ODOR_SLEUTH_MIRACLE_EYE   	 ; $c1
	const DESTINY_BOND ; $c2
	const PERISH_SONG  ; $c3
	const ICY_WIND     ; $c4
	const POWER_GEM    ; $c5
	const WILD_CHARGE  ; $c6
	const POWER_WHIP   ; $c7
	const OUTRAGE      ; $c8
	const SANDSTORM    ; $c9
	const GIGA_DRAIN   ; $ca
	const ENDURE       ; $cb
	const CHARM_FEATHER_DANCE        			; $cc
	const ROLLOUT      ; $cd
	const FALSE_SWIPE  ; $ce
	const SWAGGER      ; $cf
	const TWISTER      ; $d0
	const SPARK        ; $d1
	const ELECTRO_BALL ; $d2
	const STEEL_WING   ; $d3
	const MEAN_LOOK_BLOCK_SPIDER_WEB    		; $d4
	const ATTRACT      ; $d5 - REMOVE
	const SLEEP_TALK   ; $d6
	const HEAL_BELL    ; $d7
	const RETURN       ; $d8
	const QUIVER_DANCE ; $d9
	const BUG_BUZZ     ; $da
	const SAFEGUARD    ; $db
	const FURY_CUTTER  ; $dc
	const FAKE_OUT	   ; $dd
	const MAGNITUDE    ; $de
	const DYNAMICPUNCH ; $df
	const MEGAHORN     ; $e0
	const DRAGONBREATH ; $e1
	const BATON_PASS   ; $e2
	const ENCORE       ; $e3
	const PURSUIT      ; $e4
	const RAPID_SPIN   ; $e5
	const SHADOW_CLAW  ; $e6
	const IRON_TAIL    ; $e7
	const METAL_CLAW   ; $e8
	const AURA_SPHERE  ; $e9
	const SYNTHESIS_MOONLIGHT_MORNING_SUN 		; $ea
	const HURRICANE    ; $eb
	const KNOCK_OFF    ; $ec
	const SUPERPOWER   ; $ed
	const CROSS_CHOP   ; $ee
	const AQUA_JET     ; $ef
	const RAIN_DANCE   ; $f0
	const SUNNY_DAY    ; $f1
	const CRUNCH       ; $f2
	const MIRROR_COAT  ; $f3 -
	const NASTY_PLOT   ; $f4
	const EXTREMESPEED ; $f5
	const ANCIENTPOWER ; $f6
	const SHADOW_BALL  ; $f7
	const FUTURE_SIGHT ; $f8
	const ROCK_SMASH   ; $f9
	const WHIRLPOOL    ; $fa
	const DARK_PULSE   ; $fb
	const MOONBLAST    ; $fc
	const PLAY_ROUGH   ; $fd
	const SKULL_BASH   ; $fe
	const STRUGGLE     ; $ff

; Battle animations use the same constants
; as the moves up to this point.
	const ANIM_THROW_POKE_BALL   ; $100
	const ANIM_SEND_OUT_MON      ; $101
	const ANIM_RETURN_MON        ; $102
	const ANIM_CONFUSED          ; $103
	const ANIM_SLP               ; $104
	const ANIM_BRN               ; $105
	const ANIM_PSN               ; $106
	const ANIM_SAP               ; $107
	const ANIM_FRZ               ; $108
	const ANIM_PAR               ; $109
	const ANIM_IN_LOVE           ; $10a
	const ANIM_IN_SANDSTORM      ; $10b
	const ANIM_IN_HAIL           ; $10c
	const ANIM_UNDER_CURSE       ; $10d
	const ANIM_IN_WHIRLPOOL      ; $10e
; battle anims
	const ANIM_MISS              ; $10f
	const ANIM_ENEMY_DAMAGE      ; $110
	const ANIM_ENEMY_STAT_DOWN   ; $111
	const ANIM_PLAYER_STAT_DOWN  ; $112
	const ANIM_PLAYER_DAMAGE     ; $113
	const ANIM_WOBBLE            ; $114
	const ANIM_SHAKE             ; $115
	const ANIM_HIT_CONFUSION     ; $116
	const ANIM_SHARPEN           ; $117

; wNumHits uses offsets from ANIM_MISS
	const_def
	const BATTLEANIM_NONE
	const BATTLEANIM_ENEMY_DAMAGE
	const BATTLEANIM_ENEMY_STAT_DOWN
	const BATTLEANIM_PLAYER_STAT_DOWN
	const BATTLEANIM_PLAYER_DAMAGE
	const BATTLEANIM_WOBBLE
	const BATTLEANIM_SHAKE
	const BATTLEANIM_HIT_CONFUSION
