DEF PIANO_ROLL_HEIGHT EQU 14
DEF PIANO_ROLL_HEIGHT_PX EQU PIANO_ROLL_HEIGHT * 8

DEF MP_HUD_TOP EQU PIANO_ROLL_HEIGHT + 1
DEF MP_HUD_HEIGHT EQU SCREEN_HEIGHT - PIANO_ROLL_HEIGHT

DEF MP_LIST_CURSOR_Y EQU 8 ; (SCREEN_HEIGHT - 1) / 2
DEF MP_LIST_PAGE_SKIP EQU 10

DEF NUM_WAVEFORMS EQU 11
DEF NUM_NOISE_SETS EQU 6
DEF MAX_PITCH_TRANSPOSITION EQU 12
DEF MAX_TEMPO_ADJUSTMENT EQU 120

	const_def
	const MP_EDIT_CH1   ; 0
	const MP_EDIT_CH2   ; 1
	const MP_EDIT_WAVE  ; 2
	const MP_EDIT_NOISE ; 3
	const MP_EDIT_PITCH ; 4
	const MP_EDIT_TEMPO ; 5
DEF NUM_MP_EDIT_FIELDS EQU const_value

	const_def
	const ORIGIN_NONE    ; 00
	const ORIGIN_GSC     ; 01

	const_def
	const COMPOSER_NONE                          ; 00
	const COMPOSER_CORALDEV		                 ; 01
	const COMPOSER_CCCP			                 ; 02
	const COMPOSER_SAXOPHONE_OF_TIME		     ; 03
	const COMPOSER_JUNICHI_MASUDA                ; 04
	const COMPOSER_GO_ICHINOSE	                 ; 05
	const COMPOSER_CCCP_CORALDEV		         ; 06
	const COMPOSER_EIKO							 ; 07
	const COMPOSER_ALPHA_REMASTER				 ; 08
	const COMPOSER_MINAKO_ADACHI				 ; 09
	const COMPOSER_MUDSTEP_CORALDEV				 ; 0a
