	const_def
	const MUSIC_NONE
	const MUSIC_TITLE
	const MUSIC_SUNSET_BAY
	const MUSIC_MOM
	const MUSIC_POKEMON_CENTER
	const MUSIC_HEAL
	const MUSIC_RIVAL_ENCOUNTER
	const MUSIC_RIVAL_BATTLE
	const MUSIC_ROUTE_1
	const MUSIC_WILD_BATTLE
	const MUSIC_WILD_VICTORY
	const MUSIC_DAYBREAK_VILLAGE
	const MUSIC_ROUTE_2
	const MUSIC_YOUNGSTER_ENCOUNTER
	const MUSIC_TRAINER_BATTLE
	const MUSIC_TRAINER_VICTORY
	const MUSIC_DAYBREAK_GROTTO
	const MUSIC_GLINT_CITY
	const MUSIC_GLINT_GROVE
	const MUSIC_GYM
	const MUSIC_GYM_BATTLE
	const MUSIC_GYM_VICTORY
	const MUSIC_EVOLUTION
	const MUSIC_LASS_ENCOUNTER
	const MUSIC_SNARE_INVASION
	const MUSIC_TEAM_SNARE_ENCOUNTER
	const MUSIC_SNARE_BATTLE
	const MUSIC_SNARE_VICTORY
	const MUSIC_ENCOUNTER_GYM_LEADER
	const MUSIC_STARGLOW_VALLEY
	const MUSIC_ROUTE_4
	const MUSIC_HIKER_ENCOUNTER
	const MUSIC_LAVA
	const MUSIC_WILD_BOSS_BATTLE
	const MUSIC_MOUNTAINTOP
	const MUSIC_SUNBEAM_ISLAND
	const MUSIC_SPRUCE
	const MUSIC_SNARE_THEME
	const MUSIC_SNARE_ADMIN_BATTLE
	const MUSIC_EVENTIDE
	const MUSIC_EVENTIDE_VILLAGE
	const MUSIC_DODRIO_RACE
	const MUSIC_FLICKER_STATION
	const MUSIC_POKEMANIAC_ENCOUNTER
	const MUSIC_ROUTE_10
	const MUSIC_TWINKLE_TOWN
	const MUSIC_LUSTER_SEWER
	const MUSIC_TRAIN
	const MUSIC_LUSTER_CITY
	const MUSIC_HARDCORE_ENCOUNTER
	const MUSIC_MINIBOSS_BATTLE
	const MUSIC_ROUTE_12
	const MUSIC_WATER_ROUTE
	const MUSIC_SHIMMER_CITY
	const MUSIC_GSC_GAME_CORNER
	const MUSIC_OASIS
	const MUSIC_SNARE_LEADER_BATTLE
	const MUSIC_GENTLEMAN_ENCOUNTER
	
NUM_SONGS EQU const_value
	
	const MUSIC_CAPTURE
	const MUSIC_HALL_OF_FAME
	const MUSIC_CREDITS
	const MUSIC_POST_CREDITS
	const MUSIC_SNES_KIRBY
	const MUSIC_SNES_SMW
	const MUSIC_CORALDEV_1
	const MUSIC_CLOWN
	const MUSIC_TV_STATIC
	const MUSIC_TITLE2
	const MUSIC_RIVAL_AFTER
	const MUSIC_AFTER_TEAM_SNARE_ENCOUNTER
	const MUSIC_TRAIN_STARTUP
	const MUSIC_DEV_MESSAGE
	const MUSIC_DEV_MESSAGE_END

; special
MUSIC_STARGLOW EQU -1
MUSIC_JUNGLE EQU -2
MUSIC_TRAIN_RIDE EQU -3
MUSIC_TV_ROOM EQU -4
