PIANO_ROLL_HEIGHT EQU 14
PIANO_ROLL_HEIGHT_PX EQU PIANO_ROLL_HEIGHT * 8

MP_HUD_TOP EQU PIANO_ROLL_HEIGHT + 1
MP_HUD_HEIGHT EQU SCREEN_HEIGHT - PIANO_ROLL_HEIGHT

MP_LIST_CURSOR_Y EQU 8 ; (SCREEN_HEIGHT - 1) / 2
MP_LIST_PAGE_SKIP EQU 10

NUM_WAVEFORMS EQU 11
NUM_NOISE_SETS EQU 6
MAX_PITCH_TRANSPOSITION EQU 12
MAX_TEMPO_ADJUSTMENT EQU 120

	const_def
	const MP_EDIT_CH1   ; 0
	const MP_EDIT_CH2   ; 1
	const MP_EDIT_WAVE  ; 2
	const MP_EDIT_NOISE ; 3
	const MP_EDIT_PITCH ; 4
	const MP_EDIT_TEMPO ; 5
NUM_MP_EDIT_FIELDS EQU const_value

	const_def
	const ORIGIN_NONE    ; 00
	const ORIGIN_GSC     ; 01

	const_def
	const COMPOSER_NONE                          ; 00
	const COMPOSER_CORALDEV		                 ; 01
	const COMPOSER_CCCP			                 ; 02
	const COMPOSER_SAXOPHONE_OF_TIME		     ; 03
	const COMPOSER_JUNICHI_MASUDA                ; 04
	const COMPOSER_CCCP_CORALDEV		         ; 05
