	const_def
	const MUSIC_NONE                           ; 00
	const MUSIC_TITLE                          ; 01
	const MUSIC_TITLE2
	const MUSIC_ROUTE_2
	const MUSIC_SUNSET_BAY
	const MUSIC_MOM                            ; 02
	const MUSIC_POKEMON_CENTER                 ; 05
	const MUSIC_HEAL                           ; 06
	const MUSIC_SPRUCE
	const MUSIC_RIVAL_BATTLE                   ; 0c
	const MUSIC_TRAINER_VICTORY                ; 09
	const MUSIC_ROUTE_1
	const MUSIC_WILD_BATTLE
	const MUSIC_CAPTURE                        ; 07
	const MUSIC_WILD_VICTORY                   ; 0
	const MUSIC_DAYBREAK_VILLAGE
	const MUSIC_TRAINER_BATTLE
	const MUSIC_EVOLUTION                      ; 0e
	const MUSIC_GYM                            ; 0f
	const MUSIC_GYM_VICTORY                    ; 10
	const MUSIC_HALL_OF_FAME                   ; 16
	const MUSIC_CREDITS                        ; 19
	const MUSIC_POST_CREDITS                   ; 1a
	const MUSIC_SNES_KIRBY
	const MUSIC_SNES_SMW
	const MUSIC_DAYBREAK_GROTTO
	const MUSIC_GYM_BATTLE
	const MUSIC_GLINT_CITY
	const MUSIC_SNARE_INVASION
	const MUSIC_SNARE_BATTLE
	const MUSIC_SNARE_ADMIN_BATTLE
	const MUSIC_STARGLOW_VALLEY
	const MUSIC_ROUTE_4
	const MUSIC_CORALDEV_1
	const MUSIC_GLINT_GROVE
	const MUSIC_ROUTE_10
	const MUSIC_LUSTER_CITY
	const MUSIC_LUSTER_SEWER
	const MUSIC_TWINKLE_TOWN_DAY
	const MUSIC_TWINKLE_TOWN_NITE
	const MUSIC_LAVA
	const MUSIC_SUNBEAM_ISLAND
	const MUSIC_EVENTIDE
	const MUSIC_GSC_GAME_CORNER
	const MUSIC_DODRIO_RACE
	const MUSIC_ENCOUNTER_GYM_LEADER
	const MUSIC_RIVAL_ENCOUNTER
	const MUSIC_RIVAL_AFTER
	const MUSIC_YOUNGSTER_ENCOUNTER
	const MUSIC_LASS_ENCOUNTER
	const MUSIC_HIKER_ENCOUNTER
	const MUSIC_POKEMANIAC_ENCOUNTER
	const MUSIC_GENTLEMAN_ENCOUNTER
	const MUSIC_HARDCORE_ENCOUNTER
	const MUSIC_TEAM_SNARE_ENCOUNTER
	const MUSIC_AFTER_TEAM_SNARE_ENCOUNTER
	const MUSIC_MOUNTAINTOP
	const MUSIC_TRAIN
	const MUSIC_TRAIN_STARTUP
	const MUSIC_SNARE_THEME
	const MUSIC_WATER_ROUTE
	const MUSIC_EVENTIDE_VILLAGE
	const MUSIC_SNARE_VICTORY
	
NUM_SONGS EQU const_value

; special
MUSIC_STARGLOW EQU -1
MUSIC_JUNGLE EQU -2
MUSIC_TRAIN_RIDE EQU -3
MUSIC_TWINKLE_TOWN EQU -4
