	const_def
	const PHONE_00
	const PHONE_MOM
	const PHONE_SPRUCE
	const PHONE_WENDY
;	const PHONE_SCHOOLBOY_JACK

	const_def
	const SPECIALCALL_NONE
	const SPECIALCALL_POKERUS
	const SPECIALCALL_COMETOISLAND
	const SPECIALCALL_MOMCOMEGETTRAINERCARD
;	const SPECIALCALL_WEIRDBROADCAST
;	const SPECIALCALL_SSTICKET
;	const SPECIALCALL_BIKESHOP
;	const SPECIALCALL_WORRIED
;	const SPECIALCALL_MASTERBALL
;	const SPECIALCALL_YELLOWFOREST
;	const SPECIALCALL_FIRSTBADGE
;	const SPECIALCALL_SECONDBADGE
;	const SPECIALCALL_LYRASEGG

	const_def
	const PHONE_CONTACT_TRAINER_CLASS
	const PHONE_CONTACT_TRAINER_NUMBER
	const PHONE_CONTACT_MAP_GROUP
	const PHONE_CONTACT_MAP_NUMBER
	const PHONE_CONTACT_SCRIPT1_TIME
	const PHONE_CONTACT_SCRIPT1_BANK
	const PHONE_CONTACT_SCRIPT1_ADDR_LO
	const PHONE_CONTACT_SCRIPT1_ADDR_HI
	const PHONE_CONTACT_SCRIPT2_TIME
	const PHONE_CONTACT_SCRIPT2_BANK
	const PHONE_CONTACT_SCRIPT2_ADDR_LO
	const PHONE_CONTACT_SCRIPT2_ADDR_HI
PHONE_TABLE_WIDTH EQU const_value
CONTACT_LIST_SIZE EQU 30

; mom items
const_value = 1
	const MOM_ITEM
	const MOM_DOLL
