; strings
DEF NAME_LENGTH EQU 11
DEF PLAYER_NAME_LENGTH EQU 8
DEF BOX_NAME_LENGTH EQU 9
DEF PKMN_NAME_LENGTH EQU 11
DEF MOVE_NAME_LENGTH EQU 13
DEF ITEM_NAME_LENGTH EQU 13
DEF TRAINER_CLASS_NAME_LENGTH EQU 13
DEF TAPE_NAME_LENGTH EQU 43

; GetName types
DEF PKMN_NAME     EQU 1
DEF MOVE_NAME     EQU 2
DEF CLOTHES_NAME  EQU 3
DEF ITEM_NAME     EQU 4
DEF TAPE_NAME     EQU 5
DEF PARTY_OT_NAME EQU 6
DEF ENEMY_OT_NAME EQU 7
DEF TRAINER_NAME  EQU 8
DEF DECO_NAME	  EQU 9

; text
DEF BORDER_WIDTH   EQU 2
DEF TEXTBOX_WIDTH  EQU SCREEN_WIDTH
DEF TEXTBOX_INNERW EQU TEXTBOX_WIDTH - BORDER_WIDTH
DEF TEXTBOX_HEIGHT EQU 6
DEF TEXTBOX_INNERH EQU TEXTBOX_HEIGHT - BORDER_WIDTH
DEF TEXTBOX_X      EQU 0
DEF TEXTBOX_INNERX EQU TEXTBOX_X + 1
DEF TEXTBOX_Y      EQU SCREEN_HEIGHT - TEXTBOX_HEIGHT
DEF TEXTBOX_INNERY EQU TEXTBOX_Y + 2

; PrintNum bit flags

DEF PRINTNUM_MONEY_F        EQU 5
DEF PRINTNUM_LEFTALIGN_F    EQU 6
DEF PRINTNUM_LEADINGZEROS_F EQU 7

DEF PRINTNUM_MONEY          EQU 1 << PRINTNUM_MONEY_F
DEF PRINTNUM_LEFTALIGN      EQU 1 << PRINTNUM_LEFTALIGN_F
DEF PRINTNUM_LEADINGZEROS   EQU 1 << PRINTNUM_LEADINGZEROS_F
