; strings
DEF NAME_LENGTH EQU 11
DEF PLAYER_NAME_LENGTH EQU 8
DEF BOX_NAME_LENGTH EQU 9
DEF PKMN_NAME_LENGTH EQU 11
DEF MOVE_NAME_LENGTH EQU 13
DEF ITEM_NAME_LENGTH EQU 13
DEF TRAINER_CLASS_NAME_LENGTH EQU 13
DEF TAPE_NAME_LENGTH EQU 43

; GetName types
DEF PKMN_NAME     EQU 1
DEF MOVE_NAME     EQU 2
DEF CLOTHES_NAME  EQU 3
DEF ITEM_NAME     EQU 4
DEF TAPE_NAME     EQU 5
DEF PARTY_OT_NAME EQU 6
DEF ENEMY_OT_NAME EQU 7
DEF TRAINER_NAME  EQU 8
DEF DECO_NAME	  EQU 9

; text
DEF BORDER_WIDTH   EQU 2
DEF TEXTBOX_WIDTH  EQU SCREEN_WIDTH
DEF TEXTBOX_INNERW EQU TEXTBOX_WIDTH - BORDER_WIDTH
DEF TEXTBOX_HEIGHT EQU 6
DEF TEXTBOX_INNERH EQU TEXTBOX_HEIGHT - BORDER_WIDTH
DEF TEXTBOX_X      EQU 0
DEF TEXTBOX_INNERX EQU TEXTBOX_X + 1
DEF TEXTBOX_Y      EQU SCREEN_HEIGHT - TEXTBOX_HEIGHT
DEF TEXTBOX_INNERY EQU TEXTBOX_Y + 2

; PrintNum bit flags

DEF PRINTNUM_MONEY_F        EQU 5
DEF PRINTNUM_LEFTALIGN_F    EQU 6
DEF PRINTNUM_LEADINGZEROS_F EQU 7

DEF PRINTNUM_MONEY          EQU 1 << PRINTNUM_MONEY_F
DEF PRINTNUM_LEFTALIGN      EQU 1 << PRINTNUM_LEFTALIGN_F
DEF PRINTNUM_LEADINGZEROS   EQU 1 << PRINTNUM_LEADINGZEROS_F

;textbox names
	const_def
	const TEXTBOX_NONE
	const TEXTBOX_UNKNOWN
	const TEXTBOX_MOM
	const TEXTBOX_MINA
	const TEXTBOX_FELICIA
	const TEXTBOX_CAPTAIN
	const TEXTBOX_RIVAL
	const TEXTBOX_POPPY
	const TEXTBOX_WENDY
	const TEXTBOX_MASTER
	const TEXTBOX_STANLEY
	const TEXTBOX_RIVALS_MOM
	const TEXTBOX_LEDIAN_RANGER
	const TEXTBOX_DISGUISEMAN
	const TEXTBOX_GRUNT
	const TEXTBOX_GRUNT_A
	const TEXTBOX_GRUNT_B
	const TEXTBOX_CAGE
	const TEXTBOX_CLERK
	const TEXTBOX_PUNK
	const TEXTBOX_PUNK_BOSS
	const TEXTBOX_PUNK_A
	const TEXTBOX_PUNK_B
	const TEXTBOX_MALL_COP
	const TEXTBOX_POLLY
	const TEXTBOX_BRUTUS
	const TEXTBOX_FRANKIE
	const TEXTBOX_PA
	const TEXTBOX_CONDUCTOR
	const TEXTBOX_REPORTER
	const TEXTBOX_NETT
	const TEXTBOX_ROCKY
	const TEXTBOX_ROCKFORD
	const TEXTBOX_LOCKE
	const TEXTBOX_ABIE
	const TEXTBOX_ROSE
	const TEXTBOX_IRIS
	const TEXTBOX_VIOLET
	const TEXTBOX_CLOVER
	const TEXTBOX_LILY
	const TEXTBOX_ERIKA
	const TEXTBOX_LEILANI
	const TEXTBOX_GIRLS
	const TEXTBOX_OTTO
	const TEXTBOX_DAHLIA
	const TEXTBOX_PUSHER
	const TEXTBOX_HILL
	const TEXTBOX_CROWD
	const TEXTBOX_SPRUCE
	const TEXTBOX_LILAC
	const TEXTBOX_ASTER
	const TEXTBOX_HAZEL
	const TEXTBOX_GIRL
	const TEXTBOX_LADY
	const TEXTBOX_RODNEY
	const TEXTBOX_CHARLIE
	const TEXTBOX_BOY
	const TEXTBOX_STRAND
	const TEXTBOX_ABNER
	const TEXTBOX_EGGY
	const TEXTBOX_CRUSHER
	const TEXTBOX_BUTTERCUP
	
	const_def $ff
DEF TEXTBOX_NAMES EQU const_value
	const TEXTBOX_POKEMON
