	const_def 1
	const TILESET_PLAYER_ROOM 		;01
	const TILESET_PLAYER_HOUSE		;02
	const TILESET_GLINT				;03
	const TILESET_HOUSE_1			;04
	const TILESET_HOUSE_2			;05
	const TILESET_POKECENTER		;06
	const TILESET_MART				;07
	const TILESET_CAFE				;08
	const TILESET_LIGHTHOUSE		;09
	const TILESET_GATE				;10
	const TILESET_LAB				;11
	const TILESET_CAVE				;12
	const TILESET_STARGLOW_CAVERN	;13
	const TILESET_LAVA_CAVE			;14
	const TILESET_GROVE				;15
	const TILESET_MOUNTAIN			;16
	const TILESET_JUNGLE			;17
	const TILESET_SPOOKY			;18
	const TILESET_HAUNTED			;19
	const TILESET_HAUNTED_TV		;20
	const TILESET_RANCH				;21
	const TILESET_LUSTER			;22
	const TILESET_SNOW				;23
	const TILESET_PARK				;24
	const TILESET_MALL_1			;25
	const TILESET_MALL_2			;26
	const TILESET_SEWER				;27
	const TILESET_TRAIN				;28
	

	const_def
	const PAL_BG_GRAY   ; 0
	const PAL_BG_RED    ; 1
	const PAL_BG_GREEN  ; 2
	const PAL_BG_WATER  ; 3
	const PAL_BG_YELLOW ; 4
	const PAL_BG_BROWN  ; 5
	const PAL_BG_ROOF   ; 6
	const PAL_BG_TEXT   ; 7

	const_def $80
	const PAL_BG_PRIORITY_GRAY   ; 80
	const PAL_BG_PRIORITY_RED    ; 81
	const PAL_BG_PRIORITY_GREEN  ; 82
	const PAL_BG_PRIORITY_WATER  ; 83
	const PAL_BG_PRIORITY_YELLOW ; 84
	const PAL_BG_PRIORITY_BROWN  ; 85
	const PAL_BG_PRIORITY_ROOF   ; 86
	const PAL_BG_PRIORITY_TEXT   ; 87
