	const_def 1
	const TILESET_PLAYER_ROOM
	const TILESET_PLAYER_HOUSE
	const TILESET_SUNSET
	const TILESET_GLINT
	const TILESET_STARGLOW
	const TILESET_HOUSE_1
	const TILESET_HOUSE_2
	const TILESET_POKECENTER
	const TILESET_MART
	const TILESET_LIGHTHOUSE
	const TILESET_GATE
	const TILESET_LAB
	const TILESET_CAVE
	const TILESET_STARGLOW_CAVERN
	const TILESET_GROVE
	const TILESET_MOUNTAIN
	const TILESET_JUNGLE
	const TILESET_SPOOKY
	const TILESET_HAUNTED
	const TILESET_HAUNTED_TV
	const TILESET_RANCH
	const TILESET_LUSTER
	const TILESET_SNOW
	const TILESET_PARK
	const TILESET_MALL_1
	const TILESET_MALL_2
	const TILESET_SEWER
	const TILESET_TRAIN
	const TILESET_ICE_CAVE
	const TILESET_NETT_BUILDING
	const TILESET_SHIMMER
	const TILESET_DESERT
	const TILESET_AIRPORT
	const TILESET_ORPHANAGE
	const TILESET_HIGHWAY
	const TILESET_HIGHWAY_2
	const TILESET_DIVE
	const TILESET_BAR
	const TILESET_AUTUMN
	const TILESET_SOUTH_TOWNS
	const TILESET_GREEN_CAVE
	const TILESET_SOUTH_BUILDINGS
	const TILESET_LAVA_CAVE
	

	const_def
	const PAL_BG_GRAY   ; 0
	const PAL_BG_RED    ; 1
	const PAL_BG_GREEN  ; 2
	const PAL_BG_WATER  ; 3
	const PAL_BG_YELLOW ; 4
	const PAL_BG_BROWN  ; 5
	const PAL_BG_ROOF   ; 6
	const PAL_BG_TEXT   ; 7

	const_def $80
	const PAL_BG_PRIORITY_GRAY   ; 80
	const PAL_BG_PRIORITY_RED    ; 81
	const PAL_BG_PRIORITY_GREEN  ; 82
	const PAL_BG_PRIORITY_WATER  ; 83
	const PAL_BG_PRIORITY_YELLOW ; 84
	const PAL_BG_PRIORITY_BROWN  ; 85
	const PAL_BG_PRIORITY_ROOF   ; 86
	const PAL_BG_PRIORITY_TEXT   ; 87
