	const_def
	const TRNATTR_ITEM1
	const TRNATTR_ITEM2
	const TRNATTR_BASEMONEY
	const TRNATTR_AI_MOVE_WEIGHTS
	const TRNATTR_AI2
	const TRNATTR_AI_ITEM_SWITCH
	const TRNATTR_AI4
DEF NUM_TRAINER_ATTRIBUTES EQU const_value

	const_def
	const TRNTYPE_NORMAL
	const TRNTYPE_ITEM
	const TRNTYPE_EVS
	const TRNTYPE_DVS
	const TRNTYPE_PERSONALITY
	const TRNTYPE_NICKNAME
	const TRNTYPE_MOVES

DEF TRAINERTYPE_NORMAL      EQU TRNTYPE_NORMAL
DEF TRAINERTYPE_ITEM        EQU (1 << TRNTYPE_ITEM)
DEF TRAINERTYPE_EVS         EQU (1 << TRNTYPE_EVS)
DEF TRAINERTYPE_DVS         EQU (1 << TRNTYPE_DVS)
DEF TRAINERTYPE_PERSONALITY EQU (1 << TRNTYPE_PERSONALITY)
DEF TRAINERTYPE_NICKNAME    EQU (1 << TRNTYPE_NICKNAME)
DEF TRAINERTYPE_MOVES       EQU (1 << TRNTYPE_MOVES)

; ai

	const_def
	const       NO_AI
DEF const_value = 0
	shift_const AI_BASIC
	shift_const AI_SETUP
	shift_const AI_TYPES
	shift_const AI_OFFENSIVE
	shift_const AI_SMART
	shift_const AI_OPPORTUNIST
	shift_const AI_AGGRESSIVE
	shift_const AI_CAUTIOUS
	shift_const AI_STATUS
	shift_const AI_RISKY
	shift_const AI_10
	shift_const AI_11
	shift_const AI_12
	shift_const AI_13
	shift_const AI_14
	shift_const AI_15

DEF CONTEXT_USE_F      EQU 6
DEF UNKNOWN_USE_F      EQU 5
DEF ALWAYS_USE_F       EQU 4
DEF SWITCH_SOMETIMES_F EQU 2
DEF SWITCH_RARELY_F    EQU 1
DEF SWITCH_OFTEN_F     EQU 0

DEF CONTEXT_USE        EQU 1 << CONTEXT_USE_F
DEF UNKNOWN_USE        EQU 1 << UNKNOWN_USE_F
DEF ALWAYS_USE         EQU 1 << ALWAYS_USE_F
DEF SWITCH_SOMETIMES   EQU 1 << SWITCH_SOMETIMES_F
DEF SWITCH_RARELY      EQU 1 << SWITCH_RARELY_F
DEF SWITCH_OFTEN       EQU 1 << SWITCH_OFTEN_F
DEF SPRITE_GFX_LIST_CAPACITY EQU $20
