; wMonType: ; cf5f
DEF PARTYMON   EQU 0
DEF OTPARTYMON EQU 1
DEF BOXMON     EQU 2
DEF BREEDMON   EQU 3
DEF WILDMON    EQU 4

; Text box flags
; TODO: add the other bits used
DEF NO_LINE_SPACING EQU 2

; wOptions1: text speed
DEF INST_TEXT      EQU $0
DEF FAST_TEXT      EQU $1
DEF MED_TEXT       EQU $2
DEF SLOW_TEXT      EQU $3

; wOptions1: text autoscroll.
; CheckAutoscroll relies on exact bit usage and order
DEF AUTOSCROLL_MASK  EQU %1100
DEF AUTOSCROLL_NONE  EQU %0000
DEF AUTOSCROLL_START EQU %0100
DEF AUTOSCROLL_AANDB EQU %1000
DEF AUTOSCROLL_AORB  EQU %1100

; bits
DEF AUTOSCROLL_ABF EQU 3
DEF DEBUG_MODE	   EQU 4
DEF NO_TEXT_SCROLL EQU 5
DEF STEREO         EQU 6
DEF BATTLE_EFFECTS EQU 7

; wOptions2:
DEF FONT_MASK      EQU %00000111
DEF NORMAL_FONT    EQU %000
DEF NARROW_FONT    EQU %001
DEF BOLD_FONT      EQU %010
DEF ITALIC_FONT    EQU %011
DEF SERIF_FONT     EQU %100
DEF UNOWN_FONT     EQU %101
; bits
DEF MON_ANIMATIONS EQU 3
DEF CRY_STYLE	   EQU 4
DEF POKEDEX_UNITS  EQU 5
DEF BATTLE_SWITCH  EQU 6
DEF BATTLE_PREDICT EQU 7

; wInitialOptions:
DEF NATURES_OPT      EQU 0
DEF ABILITIES_OPT    EQU 1
DEF COLOR_VARY_OPT   EQU 2
DEF PERFECT_IVS_OPT  EQU 3
DEF TRADED_AS_OT_OPT EQU 4
DEF NUZLOCKE_MODE    EQU 5
DEF RESET_INIT_OPTS  EQU 7
DEF ABILITIES_OPTMASK EQU %00000010

; wForgettingMove
DEF FORGETTING_MOVE_F EQU 7
DEF LEARNING_TM_F     EQU 6
DEF FORGETTING_MOVE   EQU 1 << FORGETTING_MOVE_F
DEF LEARNING_TM       EQU 1 << LEARNING_TM_F

; wWalkingDirection: ; d043
DEF STANDING EQU -1
DEF DOWN     EQU 0
DEF UP       EQU 1
DEF LEFT     EQU 2
DEF RIGHT    EQU 3

; wFacingDirection: ; d044
DEF FACE_CURRENT EQU 0
DEF FACE_DOWN  EQU 8
DEF FACE_UP    EQU 4
DEF FACE_LEFT  EQU 2
DEF FACE_RIGHT EQU 1

; wTimeOfDay: ; d269
DEF MORN     EQU 0
DEF DAY      EQU 1
DEF NITE     EQU 2
DEF DUSK EQU 3

; wScriptFlags: ; d434
DEF SCRIPT_RUNNING EQU 2

; wScriptMode: ; d437
DEF SCRIPT_OFF EQU 0
DEF SCRIPT_READ EQU 1
DEF SCRIPT_WAIT_MOVEMENT EQU 2
DEF SCRIPT_WAIT EQU 3

; wCurDay: ; d4cb
DEF SUNDAY    EQU 0
DEF MONDAY    EQU 1
DEF TUESDAY   EQU 2
DEF WEDNESDAY EQU 3
DEF THURSDAY  EQU 4
DEF FRIDAY    EQU 5
DEF SATURDAY  EQU 6

; wMapObjects: ; d71e
DEF PLAYER_OBJECT EQU 0
DEF NUM_OBJECTS EQU $15

; wInputType: ; c2c7
DEF AUTO_INPUT EQU $ff

; wOWState
DEF OWSTATE_STRENGTH        EQU 0
DEF OWSTATE_BIKING_FORCED   EQU 1
DEF OWSTATE_BIKING_DOWNHILL EQU 2
DEF OWSTATE_SURF            EQU 3
DEF OWSTATE_ROCK_SMASH      EQU 4
DEF OWSTATE_HEADBUTT        EQU 5
DEF OWSTATE_WHIRLPOOL       EQU 6
DEF OWSTATE_WATERFALL       EQU 7
DEF OWSTATE_CUT             EQU 8
DEF OWSTATE_BIKE_GEAR       EQU 9
DEF OWSTATE_ROCK_CLIMB      EQU 10

; wPlayerState:
	const_def
	const PLAYER_NORMAL
	const PLAYER_BIKE
	const PLAYER_SURF
	const PLAYER_DIVE
	const PLAYER_RUN
	const PLAYER_SURF_LAVA
	const PLAYER_DODRIO
	const PLAYER_SITTING
	const PLAYER_SKATEBOARD
	const PLAYER_SKATEBOARD_MOVING
	const PLAYER_SKATEBOARD_GRINDING
	const PLAYER_FALLING
	const PLAYER_BATHING
	const PLAYER_CLOWN
	const PLAYER_SAND
	const PLAYER_SCIENTIST
	const PLAYER_COLBY
	const PLAYER_INVISIBLE
	const PLAYER_PHOTO_1
	const PLAYER_PHOTO_2
	const PLAYER_PHOTO_3
	const PLAYER_PHOTO_4
	const PLAYER_SNARE
DEF NUM_PLAYER_STATE_SPRITES EQU const_value
	const PLAYER_SLIP
DEF NUM_PLAYER_STATES EQU const_value

DEF OBJECT_STRUCT_LENGTH EQU 33
DEF NUM_OBJECT_STRUCTS EQU 13
DEF FIRST_VRAM1_OBJECT_STRUCT EQU 8

; After-Champion Spawn
DEF SPAWN_LANCE EQU 1
DEF SPAWN_LEAF EQU 2

; wPokemonWithdrawDepositParameter
DEF PC_WITHDRAW EQU 0
DEF PC_DEPOSIT EQU 1
DEF DAYCARE_WITHDRAW EQU 2
DEF DAYCARE_DEPOSIT EQU 3

; wPalFadeMode
DEF PALFADE_WHICH       EQU %11
DEF PALFADE_FLASH_F     EQU 2
DEF PALFADE_PARTIAL_F   EQU 3
DEF PALFADE_SKIP_LAST_F EQU 4

DEF PALFADE_BOTH      EQU %00
DEF PALFADE_BG        EQU %01
DEF PALFADE_OBJ       EQU %10
DEF PALFADE_FLASH     EQU 1 << PALFADE_FLASH_F
DEF PALFADE_PARTIAL   EQU 1 << PALFADE_PARTIAL_F
DEF PALFADE_SKIP_LAST EQU 1 << PALFADE_SKIP_LAST_F

; wCurrentDexMode
	const_def
	const DEXMODE_NEW
	const DEXMODE_OLD
	const DEXMODE_ABC
	const DEXMODE_UNOWN

; wHiddenGrottoContents
	const_def
	const GROTTO_UNDEFINED
	const GROTTO_POKEMON
	const GROTTO_ITEM
	const GROTTO_HIDDEN_ITEM
	const GROTTO_EMPTY

	const_def
	const FIRSTBADGE
	const SECONDBADGE
	const THIRDBADGE
	const FOURTHBADGE
	const FIFTHBADGE
	const SIXTHBADGE
	const SEVENTHBADGE
	const EIGHTHBADGE
DEF NUM_ONWA_BADGES EQU const_value
DEF NUM_BADGES EQU NUM_ONWA_BADGES

	const_def
	const GOT_ROCK_SMASH
	const GOT_CUT
	const GOT_FLY
	const GOT_ROCK_CLIMB
	const GOT_SURF
	const GOT_DIVE
	const GOT_STRENGTH
DEF NUM_GOT_HM_FLAGS EQU const_value

	const_def
	const MET_STANLEY
	const MET_RODNEY
	const MET_WENDY
	const MET_CHARLIE
	const MET_POLLY
	const MET_LEILANI
	const MET_ROCKY
	const MET_DARCY
DEF NUM_GYM_LEADERS_MET EQU const_value

	const_def
	const PUNKS_IN_STARGLOW
	const PUNKS_ON_SUNBEAM
	const PUNKS_ON_TRAIN
DEF NUM_SNARE_FLAGS EQU const_value
