MartClerks::
	ld a, [wPlaceBallsY]
	ld hl, MartClerkPics
	ld e, a
	ld d, 0
	add hl, de
	add hl, de
	ld c, [hl]
	ld e, 1
	ld d, 0
	add hl, de
	ld a, [hl]
	push af
	ld a, c
	ld bc, 20 tiles
	ld hl, RegisterGFX
	ld e, BANK(RegisterGFX)
	rst AddNTimes
	ld b, e
	ld c, 20
	ld d, h
	ld e, l
	ld hl, VTiles2 tile $50
	call Get2bpp
	pop af
	ld [wPlaceBallsY], a
	ret
	
MartClerkPics:
	db PIC_FATTY_CLERK,				PAL_CUTIE_CLERK_GREEN	 	; MART_SUNSET
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_GLINT
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_STARGLOW
	db PIC_SEXY_CLERK,				PAL_SEXY_CLERK_PINK			; MART_ROUTE_5_GATE
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_LAKE_ONWA
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_SUNBEAM
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_EVENTIDE
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_FLICKER
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_TWINKLE
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_LUSTER
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_RED	 	; MART_LUSTER_MALL_ELECTRONICS
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_RED	 	; MART_LUSTER_MALL_ELECTRONICS_TM
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_PURPLE	; MART_LUSTER_MALL_COFFEE
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_PURPLE	; MART_LUSTER_MALL_COFFEE2
	db PIC_CUTIE_CLERK,				PAL_STANDARD_CLERK_BROWN 	; MART_LUSTER_MALL_ANTIQUE
	db PIC_LADY_CLERK,				PAL_CUTIE_CLERK_GREEN	 	; MART_LUSTER_MALL_HERB
	db PIC_FATTY_CLERK,				PAL_STANDARD_CLERK_PURPLE 	; MART_LUSTER_MALL_STONE
	db PIC_GOTH_CLERK,				PAL_GOTH_CLERK_PURPLE 		; MART_LUSTER_MALL_CLOTHES
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BROWN 	; MART_LUSTER_MALL_BALL_1
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BROWN 	; MART_LUSTER_MALL_BALL_2
	db PIC_SAILOR_CLERK,			PAL_SAILOR_CLERK_BLUE 		; MART_SHIMMER_FISH_MARKET
	db PIC_LADY_CLERK,				PAL_LADY_CLERK_RED		 	; MART_SHIMMER_BERRY_MARKET
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_SHIMMER
	db PIC_SAILOR_CLERK,			PAL_SAILOR_CLERK_RED 		; MART_BRILLO
	db PIC_SAILOR_CLERK,			PAL_SAILOR_CLERK_RED 		; MART_COINS
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_RADIANT
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_DUSK
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_KOMORE
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_RED	 	; MART_LUSTER_MALL_ELECTRONICS_DECO
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_LUSTER_MALL_FURNITURE
	db PIC_MOOMOOS_CLERK,			PAL_MOOMOOS_CLERK	 		; MART_MOOMOOS_1
	db PIC_MOOMOOS_CLERK,			PAL_MOOMOOS_CLERK	 		; MART_MOOMOOS_2
	db PIC_SEXY_CLERK,				PAL_STANDARD_CLERK_PURPLE 	; MART_SHIMMER_CAFE
	db PIC_CUTIE_CLERK,				PAL_CUTIE_CLERK_GREEN		; MART_POLLEN
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_CELADON_5F_1
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_CELADON_5F_2
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_SAFFRON
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_SILPH_CO
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_FUCHSIA
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_SHAMOUTI_1
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_SHAMOUTI_2
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_BT_1
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_BT_2
	db PIC_STANDARD_CLERK,			PAL_STANDARD_CLERK_BLUE 	; MART_BT_3
	