Cries:
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Oddish
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Shroomish
	dba Cry_Meditite
	dba Cry_Pidgey
	dba Cry_Bulbasaur
	dba Cry_Farfetch_d
	dba Cry_Krokorok
	dba Cry_Golem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Venipede
	dba Cry_Pikipek
	dba Cry_Minccino
	dba Cry_Shellder
	dba Cry_Clefairy
	dba Cry_Venonat
	dba Cry_Lapras
	dba Cry_Trumbeak
	dba Cry_Squirtle
	dba Cry_Dwebble
	dba Cry_Growlithe
	dba Cry_Carvanha
	dba Cry_Psyduck
	dba Cry_Rattata
	dba Cry_Vileplume
	dba Cry_Buizel
	dba Cry_Weepinbell
	dba Cry_Spearow
	dba Cry_Spinarak
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Togetic
	dba Cry_Hoothoot
	dba Cry_Sentret
	dba Cry_Slowking
	dba Cry_Cyndaquil
	dba Cry_Chikorita
	dba Cry_Totodile
	dba Cry_Gligar
	dba Cry_Bellossom
	dba Cry_Slugma
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Mantine
	dba Cry_Typhlosion
	dba Cry_Natu
	dba Cry_Teddiursa
	dba Cry_Remoraid
	dba Cry_Ampharos
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Tyrogue
	dba Cry_Dunsparce
	dba Cry_Donphan
; gen 3
	dba Cry_Wingull
	dba Cry_Pelipper
	dba Cry_Shroomish
	dba Cry_Breloom
	dba Cry_Aron
	dba Cry_Lairon
	dba Cry_Aggron
	dba Cry_Meditite
	dba Cry_Medicham
	dba Cry_Carvanha
	dba Cry_Sharpedo
	dba Cry_Numel
	dba Cry_Camerupt
	dba Cry_Swablu
	dba Cry_Altaria
	dba Cry_Snorunt
	dba Cry_Glalie
; gen 4
	dba Cry_Leafeon
	dba Cry_Glaceon
	dba Cry_Froslass
; gen 5
	dba Cry_Drilbur
	dba Cry_Excadrill
	dba Cry_Venipede
	dba Cry_Whirlipede
	dba Cry_Scolipede
; gen 6
	dba Cry_Sylveon
	dba Cry_Noibat
	dba Cry_Noivern
; gen 7
; gen 8
; gen 9
