Music:
	dba Music_Nothing
	dba Music_TitleScreen
	dba Music_Route2
	dba Music_SunsetBay
	dba Music_Mom
	dba Music_PokemonCenter
	dba Music_HealPokemon
	dba Music_SpruceLab
	dba Music_RivalBattle
	dba Music_TrainerVictory
	dba Music_Route1
	dba Music_WildBattle
	dba Music_SuccessfulCapture
	dba Music_WildPokemonVictory
	dba Music_DayBreakVillage
	dba Music_TrainerBattle
	dba Music_Evolution
	dba Music_Gym
	dba Music_GymLeaderVictory
	dba Music_HallOfFame
	dba Music_Credits
	dba Music_PostCredits
	dba Music_Snes_Kirby
	dba Music_Snes_Smw
	dba Music_DayBreakGrotto
	dba Music_GymBattle
	dba Music_GlintCity
	dba Music_SnareInvasion
	dba Music_SnareBattle
	dba Music_SnareAdminBattle
	dba Music_StarglowValley
	dba Music_Route4
	dba Music_Coraldev1
	dba Music_GlintGrove
	dba Music_Route10
	dba Music_LusterCity
	dba Music_LusterSewer
	dba Music_TwinkleTownDay
	dba Music_TwinkleTownNite
	dba Music_Lava
	dba Music_SunbeamIsland
	dba Music_Eventide
	dba Music_GscGameCorner
	dba Music_DodrioRace
	dba Music_EncounterGymLeader
	dba Music_RivalEncounter
	dba Music_AfterTheRivalFight
	dba Music_YoungsterEncounter
	dba Music_LassEncounter
	dba Music_HikerEncounter
	dba Music_PokemaniacEncounter
	dba Music_GentlemanEncounter
	dba Music_HardcoreEncounter
	dba Music_TeamSnareEncounter
	dba Music_AfterTeamSnareEncounter
	dba Music_Mountaintop
	dba Music_Train
	dba Music_TrainStartup
	dba Music_SnareTheme
	dba Music_WaterRoute
	