Music:
	dba Music_Nothing
	dba Music_TitleScreen
	dba Music_Route2
	dba Music_SunsetBay
	dba Music_Mom
	dba Music_PokemonCenter
	dba Music_HealPokemon
	dba Music_ElmsLab
	dba Music_LookRival
	dba Music_RivalBattle
	dba Music_AfterTheRivalFight
	dba Music_TrainerVictory
	dba Music_Route1
	dba Music_WildBattle
	dba Music_SuccessfulCapture
	dba Music_WildPokemonVictory
	dba Music_DayBreakVillage
	dba Music_LookYoungster
	dba Music_TrainerBattle
	dba Music_LookSage
	dba Music_Evolution
	dba Music_Gym
	dba Music_GymLeaderVictory
	dba Music_LookLass
	dba Music_LookKimonoGirl
	dba Music_LookMysticalMan
	dba Music_LookPokemaniac
	dba Music_LookBeauty
	dba Music_HallOfFame
	dba Music_LookHiker
	dba Music_LookOfficer
	dba Music_Credits
	dba Music_PostCredits
	dba Music_Snes_Kirby
	dba Music_Snes_Smw
	dba Music_WildBattle_Shiny
	dba Music_WildBattle_Shiny_Intro
	dba Music_DayBreakGrotto
	dba Music_GymBattle
	dba Music_GlintCity
	dba Music_Route4
	dba Music_Coraldev1
	dba Music_GlintGrove
	dba Music_Route10
	dba Music_Luster
	dba Music_LusterSewer
	dba Music_SnowTown
	dba Music_Lava
	