SECTION "DED 1", ROMX
PikipekDEDData:: INCBIN "audio/ded/pikipek.ded"
TrumbeakDEDData:: INCBIN "audio/ded/trumbeak.ded"
ToucannonDEDData:: INCBIN "audio/ded/toucannon.ded"

SECTION "DED 2", ROMX

SECTION "DED 3", ROMX

SECTION "DED 4", ROMX

SECTION "DED 5", ROMX

SECTION "DED 6", ROMX

SECTION "DED 7", ROMX

SECTION "DED 8", ROMX

SECTION "DED 9", ROMX

SECTION "DED 10", ROMX

SECTION "DED 11", ROMX

SECTION "DED 12", ROMX

SECTION "DED 13", ROMX

SECTION "DED 14", ROMX

SECTION "DED 15", ROMX

SECTION "DED 16", ROMX

SECTION "DED 17", ROMX

SECTION "DED 18", ROMX

SECTION "DED 19", ROMX

SECTION "DED 20", ROMX

SECTION "DED 21", ROMX

SECTION "DED 22", ROMX

SECTION "DED 23", ROMX

SECTION "DED 24", ROMX

SECTION "DED 25", ROMX

SECTION "DED 26", ROMX

SECTION "DED 27", ROMX

; The following files have been relocated to optimize bank allocation

SECTION "DED small 1", ROMX

SECTION "DED small 2", ROMX

SECTION "DED small 3", ROMX

SECTION "DED small 4", ROMX

SECTION "DED small 5", ROMX

SECTION "DED small 6", ROMX

SECTION "DED small 7", ROMX

SECTION "DED small 8", ROMX

SECTION "DED small 9", ROMX

SECTION "DED small 10", ROMX
