AnimationPointers:
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw -1 ; see  PidgeyAnimationPointers
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw -1 ; see  RattataAnimationPointers
	dw -1 ; see  RaticateAnimationPointers
	dw PikachuAnimation
	dw -1 ; see RaichuAnimationPointers
	dw -1 ; see SandshrewAnimationPointers
	dw -1 ; see SandslashAnimationPointers
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw OddishAnimation
	dw GloomAnimation
	dw VileplumeAnimation
	dw -1 ; see MeowthAnimationPointers
	dw -1 ; see PersianAnimationPointers
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw MachopAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw -1 ; see GrimerAnimationPointers
	dw -1 ; see MukAnimationPointers
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw -1 ; see ExeggcuteAnimationPointers
	dw -1 ; see ExeggutorAnimationPointers
	dw CuboneAnimation
	dw -1 ; see MarowakAnimationPointers
	dw KoffingAnimation
	dw WeezingAnimation
	dw ChanseyAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw ScytherAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw TaurosAnimation
	dw MagikarpAnimation
	dw -1 ; see  GyaradosAnimationPointers
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw BellossomAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw -1 ; see WooperAnimationPointers
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw SlowkingAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw ScizorAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw -1 ; see CorsolaAnimationPointers
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw WingullAnimation
	dw PelipperAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw MedititeAnimation
	dw MedichamAnimation
	dw CarvanhaAnimation
	dw SharpedoAnimation
	dw NumelAnimation
	dw CameruptAnimation
	dw CacneaAnimation
	dw CacturneAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw SnoruntAnimation
	dw GlalieAnimation
	dw BuizelAnimation
	dw FloatzelAnimation
	dw CherubiAnimation
	dw -1 ; see CherrimAnimationPointers
	dw DrifloonAnimation
	dw DrifblimAnimation
	dw BunearyAnimation
	dw LopunnyAnimation
	dw HonchkrowAnimation
	dw SpiritombAnimation
	dw MunchlaxAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw CroagunkAnimation
	dw ToxicroakAnimation
	dw SnoverAnimation
	dw AbomasnowAnimation
	dw WeavileAnimation
	dw MagnezoneAnimation
	dw ElectivireAnimation
	dw MagmortarAnimation
	dw TogekissAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw GliscorAnimation
	dw MamoswineAnimation
	dw PorygonZAnimation
	dw GalladeAnimation
	dw FroslassAnimation
	dw DrilburAnimation
	dw ExcadrillAnimation
	dw VenipedeAnimation
	dw WhirlipedeAnimation
	dw ScolipedeAnimation
	dw CottoneeAnimation
	dw WhimsicottAnimation
	dw SandileAnimation
	dw KrokorokAnimation
	dw KrookodileAnimation
	dw MaractusAnimation
	dw DwebbleAnimation
	dw CrustleAnimation
	dw ScraggyAnimation
	dw ScraftyAnimation
	dw TirtougaAnimation
	dw CarracostaAnimation
	dw ArchenAnimation
	dw ArcheopsAnimation
	dw MinccinoAnimation
	dw CinccinoAnimation
	dw JoltikAnimation
	dw GalvantulaAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw LarvestaAnimation
	dw VolcaronaAnimation
	dw SylveonAnimation
	dw PhantumpAnimation
	dw TrevenantAnimation
	dw NoibatAnimation
	dw NoivernAnimation
	dw PikipekAnimation
	dw TrumbeakAnimation
	dw ToucannonAnimation
	dw MareanieAnimation
	dw ToxapexAnimation
	dw -1 ; see MimikyuAnimationPointers
	dw CursolaAnimation
	dw DreepyAnimation
	dw DrakloakAnimation
	dw DragapultAnimation
	dw WyrdeerAnimation
	dw ClodsireAnimation
	dw FarigirafAnimation
	dw BulbasaurAnimation
	dw EggAnimation