BitmasksPointers:
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw ChanseyBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw ScytherBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw ScizorBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw WingullBitmasks
	dw PelipperBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw MedititeBitmasks
	dw MedichamBitmasks
	dw CarvanhaBitmasks
	dw SharpedoBitmasks
	dw NumelBitmasks
	dw CameruptBitmasks
	dw CacneaBitmasks
	dw CacturneBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw SnoruntBitmasks
	dw GlalieBitmasks
	dw BuizelBitmasks
	dw FloatzelBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw HonchkrowBitmasks
	dw SpiritombBitmasks
	dw MunchlaxBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw SnoverBitmasks
	dw AbomasnowBitmasks
	dw WeavileBitmasks
	dw MagnezoneBitmasks
	dw ElectivireBitmasks
	dw MagmortarBitmasks
	dw TogekissBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw GliscorBitmasks
	dw MamoswineBitmasks
	dw PorygonZBitmasks
	dw GalladeBitmasks
	dw FroslassBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw VenipedeBitmasks
	dw WhirlipedeBitmasks
	dw ScolipedeBitmasks
	dw CottoneeBitmasks
	dw WhimsicottBitmasks
	dw SandileBitmasks
	dw KrokorokBitmasks
	dw KrookodileBitmasks
	dw MaractusBitmasks
	dw DwebbleBitmasks
	dw CrustleBitmasks
	dw ScraggyBitmasks
	dw ScraftyBitmasks
	dw TirtougaBitmasks
	dw CarracostaBitmasks
	dw ArchenBitmasks
	dw ArcheopsBitmasks
	dw MinccinoBitmasks
	dw CinccinoBitmasks
	dw JoltikBitmasks
	dw GalvantulaBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw LarvestaBitmasks
	dw VolcaronaBitmasks
	dw SylveonBitmasks
	dw PhantumpBitmasks
	dw TrevenantBitmasks
	dw NoibatBitmasks
	dw NoivernBitmasks
	dw PikipekBitmasks
	dw TrumbeakBitmasks
	dw ToucannonBitmasks
	dw MareanieBitmasks
	dw ToxapexBitmasks
	dw WyrdeerBitmasks
	dw Raichu_ABitmasks
	dw ExeggcuteBitmasks
	dw Exeggutor_ABitmasks
	dw Marowak_ABitmasks
	dw Grimer_ABitmasks
	dw Muk_ABitmasks
	dw EggBitmasks
	dw -1 ; unused
