AnimationExtraPointers:
	dw BulbasaurAnimationExtra
	dw IvysaurAnimationExtra
	dw VenusaurAnimationExtra
	dw CharmanderAnimationExtra
	dw CharmeleonAnimationExtra
	dw CharizardAnimationExtra
	dw SquirtleAnimationExtra
	dw WartortleAnimationExtra
	dw BlastoiseAnimationExtra
	dw PidgeyAnimationExtra
	dw PidgeottoAnimationExtra
	dw PidgeotAnimationExtra
	dw RattataAnimationExtra
	dw RaticateAnimationExtra
	dw PikachuAnimationExtra
	dw RaichuAnimationExtra
	dw SandshrewAnimationExtra
	dw SandslashAnimationExtra
	dw NidoranFAnimationExtra
	dw NidorinaAnimationExtra
	dw NidoqueenAnimationExtra
	dw NidoranMAnimationExtra
	dw NidorinoAnimationExtra
	dw NidokingAnimationExtra
	dw ClefairyAnimationExtra
	dw ClefableAnimationExtra
	dw JigglypuffAnimationExtra
	dw WigglytuffAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw OddishAnimationExtra
	dw GloomAnimationExtra
	dw VileplumeAnimationExtra
	dw MeowthAnimationExtra
	dw PersianAnimationExtra
	dw GrowlitheAnimationExtra
	dw ArcanineAnimationExtra
	dw PoliwagAnimationExtra
	dw PoliwhirlAnimationExtra
	dw PoliwrathAnimationExtra
	dw AbraAnimationExtra
	dw KadabraAnimationExtra
	dw AlakazamAnimationExtra
	dw MachopAnimationExtra
	dw MachokeAnimationExtra
	dw MachampAnimationExtra
	dw GeodudeAnimationExtra
	dw GravelerAnimationExtra
	dw GolemAnimationExtra
	dw PonytaAnimationExtra
	dw RapidashAnimationExtra
	dw SlowpokeAnimationExtra
	dw SlowbroAnimationExtra
	dw MagnemiteAnimationExtra
	dw MagnetonAnimationExtra
	dw DoduoAnimationExtra
	dw DodrioAnimationExtra
	dw GrimerAnimationExtra
	dw MukAnimationExtra
	dw GastlyAnimationExtra
	dw HaunterAnimationExtra
	dw GengarAnimationExtra
	dw OnixAnimationExtra
	dw VoltorbAnimationExtra
	dw ElectrodeAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorAnimationExtra
	dw CuboneAnimationExtra
	dw MarowakAnimationExtra
	dw KoffingAnimationExtra
	dw WeezingAnimationExtra
	dw ChanseyAnimationExtra
	dw HorseaAnimationExtra
	dw SeadraAnimationExtra
	dw StaryuAnimationExtra
	dw StarmieAnimationExtra
	dw ScytherAnimationExtra
	dw ElectabuzzAnimationExtra
	dw MagmarAnimationExtra
	dw TaurosAnimationExtra
	dw MagikarpAnimationExtra
	dw GyaradosAnimationExtra
	dw LaprasAnimationExtra
	dw DittoAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw PorygonAnimationExtra
	dw AerodactylAnimationExtra
	dw SnorlaxAnimationExtra
	dw DratiniAnimationExtra
	dw DragonairAnimationExtra
	dw DragoniteAnimationExtra
	dw ChikoritaAnimationExtra
	dw BayleefAnimationExtra
	dw MeganiumAnimationExtra
	dw CyndaquilAnimationExtra
	dw QuilavaAnimationExtra
	dw TyphlosionAnimationExtra
	dw TotodileAnimationExtra
	dw CroconawAnimationExtra
	dw FeraligatrAnimationExtra
	dw LedybaAnimationExtra
	dw LedianAnimationExtra
	dw CrobatAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw TogepiAnimationExtra
	dw TogeticAnimationExtra
	dw NatuAnimationExtra
	dw XatuAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw BellossomAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw SudowoodoAnimationExtra
	dw PolitoedAnimationExtra
	dw WooperAnimationExtra
	dw QuagsireAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw MurkrowAnimationExtra
	dw SlowkingAnimationExtra
	dw PinecoAnimationExtra
	dw ForretressAnimationExtra
	dw GligarAnimationExtra
	dw SteelixAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw ScizorAnimationExtra
	dw HeracrossAnimationExtra
	dw SneaselAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw SlugmaAnimationExtra
	dw MagcargoAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw CorsolaAnimationExtra
	dw SkarmoryAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw KingdraAnimationExtra
	dw PhanpyAnimationExtra
	dw DonphanAnimationExtra
	dw Porygon2AnimationExtra
	dw StantlerAnimationExtra
	dw SmeargleAnimationExtra
	dw ElekidAnimationExtra
	dw MagbyAnimationExtra
	dw MiltankAnimationExtra
	dw BlisseyAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw WingullAnimationExtra
	dw PelipperAnimationExtra
	dw RaltsAnimationExtra
	dw KirliaAnimationExtra
	dw GardevoirAnimationExtra
	dw ShroomishAnimationExtra
	dw BreloomAnimationExtra
	dw AronAnimationExtra
	dw LaironAnimationExtra
	dw AggronAnimationExtra
	dw MedititeAnimationExtra
	dw MedichamAnimationExtra
	dw CarvanhaAnimationExtra
	dw SharpedoAnimationExtra
	dw NumelAnimationExtra
	dw CameruptAnimationExtra
	dw CacneaAnimationExtra
	dw CacturneAnimationExtra
	dw SwabluAnimationExtra
	dw AltariaAnimationExtra
	dw SnoruntAnimationExtra
	dw GlalieAnimationExtra
	dw BuizelAnimationExtra
	dw FloatzelAnimationExtra
	dw DrifloonAnimationExtra
	dw DrifblimAnimationExtra
	dw BunearyAnimationExtra
	dw LopunnyAnimationExtra
	dw HonchkrowAnimationExtra
	dw SpiritombAnimationExtra
	dw MunchlaxAnimationExtra
	dw RioluAnimationExtra
	dw LucarioAnimationExtra
	dw CroagunkAnimationExtra
	dw ToxicroakAnimationExtra
	dw SnoverAnimationExtra
	dw AbomasnowAnimationExtra
	dw WeavileAnimationExtra
	dw MagnezoneAnimationExtra
	dw ElectivireAnimationExtra
	dw MagmortarAnimationExtra
	dw TogekissAnimationExtra
	dw LeafeonAnimationExtra
	dw GlaceonAnimationExtra
	dw GliscorAnimationExtra
	dw MamoswineAnimationExtra
	dw PorygonZAnimationExtra
	dw GalladeAnimationExtra
	dw FroslassAnimationExtra
	dw DrilburAnimationExtra
	dw ExcadrillAnimationExtra
	dw VenipedeAnimationExtra
	dw WhirlipedeAnimationExtra
	dw ScolipedeAnimationExtra
	dw CottoneeAnimationExtra
	dw WhimsicottAnimationExtra
	dw SandileAnimationExtra
	dw KrokorokAnimationExtra
	dw KrookodileAnimationExtra
	dw MaractusAnimationExtra
	dw DwebbleAnimationExtra
	dw CrustleAnimationExtra
	dw ScraggyAnimationExtra
	dw ScraftyAnimationExtra
	dw TirtougaAnimationExtra
	dw CarracostaAnimationExtra
	dw ArchenAnimationExtra
	dw ArcheopsAnimationExtra
	dw MinccinoAnimationExtra
	dw CinccinoAnimationExtra
	dw JoltikAnimationExtra
	dw GalvantulaAnimationExtra
	dw LitwickAnimationExtra
	dw LampentAnimationExtra
	dw ChandelureAnimationExtra
	dw LarvestaAnimationExtra
	dw VolcaronaAnimationExtra
	dw SylveonAnimationExtra
	dw PhantumpAnimationExtra
	dw TrevenantAnimationExtra
	dw NoibatAnimationExtra
	dw NoivernAnimationExtra
	dw PikipekAnimationExtra
	dw TrumbeakAnimationExtra
	dw ToucannonAnimationExtra
	dw MareanieAnimationExtra
	dw ToxapexAnimationExtra
	dw WyrdeerAnimationExtra
	dw Raichu_AAnimationExtra
	dw ExeggcuteAnimationExtra
	dw Exeggutor_AAnimationExtra
	dw Marowak_AAnimationExtra
	dw Grimer_AAnimationExtra
	dw Muk_AAnimationExtra
	dw EggAnimationExtra
	dw -1 ; unused
