AnimationExtraPointers:
	dw BulbasaurAnimationExtra
	dw IvysaurAnimationExtra
	dw VenusaurAnimationExtra
	dw CharmanderAnimationExtra
	dw CharmeleonAnimationExtra
	dw CharizardAnimationExtra
	dw SquirtleAnimationExtra
	dw WartortleAnimationExtra
	dw BlastoiseAnimationExtra
	dw -1 ; see PidgeyAnimationExtraPointers
	dw PidgeottoAnimationExtra
	dw PidgeotAnimationExtra
	dw -1 ; see RattataAnimationExtraPointers
	dw -1 ; see  RaticateAnimationExtraPointers
	dw PikachuAnimationExtra
	dw -1 ; see RaichuAnimationExtraPointers
	dw SandshrewAnimationExtra
	dw SandslashAnimationExtra
	dw NidoranFAnimationExtra
	dw NidorinaAnimationExtra
	dw NidoqueenAnimationExtra
	dw NidoranMAnimationExtra
	dw NidorinoAnimationExtra
	dw NidokingAnimationExtra
	dw ClefairyAnimationExtra
	dw ClefableAnimationExtra
	dw JigglypuffAnimationExtra
	dw WigglytuffAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw OddishAnimationExtra
	dw GloomAnimationExtra
	dw VileplumeAnimationExtra
	dw -1 ; see MeowthAnimationExtraPointers
	dw -1 ; see PersianAnimationExtraPointers
	dw GrowlitheAnimationExtra
	dw ArcanineAnimationExtra
	dw PoliwagAnimationExtra
	dw PoliwhirlAnimationExtra
	dw PoliwrathAnimationExtra
	dw MachopAnimationExtra
	dw MachokeAnimationExtra
	dw MachampAnimationExtra
	dw GeodudeAnimationExtra
	dw GravelerAnimationExtra
	dw GolemAnimationExtra
	dw PonytaAnimationExtra
	dw RapidashAnimationExtra
	dw SlowpokeAnimationExtra
	dw SlowbroAnimationExtra
	dw MagnemiteAnimationExtra
	dw MagnetonAnimationExtra
	dw DoduoAnimationExtra
	dw DodrioAnimationExtra
	dw -1 ; see GrimerAnimationExtraPointers
	dw -1 ; see MukAnimationExtraPointers
	dw GastlyAnimationExtra
	dw HaunterAnimationExtra
	dw GengarAnimationExtra
	dw OnixAnimationExtra
	dw DrowzeeAnimationExtra
	dw HypnoAnimationExtra
	dw VoltorbAnimationExtra
	dw ElectrodeAnimationExtra
	dw -1 ; see ExeggcuteAnimationExtraPointers
	dw -1 ; see ExeggutorAnimationExtraPointers
	dw CuboneAnimationExtra
	dw -1 ; see MarowakAnimationExtraPointers
	dw KoffingAnimationExtra
	dw WeezingAnimationExtra
	dw ChanseyAnimationExtra
	dw StaryuAnimationExtra
	dw StarmieAnimationExtra
	dw ScytherAnimationExtra
	dw ElectabuzzAnimationExtra
	dw MagmarAnimationExtra
	dw TaurosAnimationExtra
	dw MagikarpAnimationExtra
	dw -1 ; see  GyaradosAnimationExtraPointers
	dw LaprasAnimationExtra
	dw DittoAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw PorygonAnimationExtra
	dw AerodactylAnimationExtra
	dw SnorlaxAnimationExtra
	dw ArticunoAnimationExtra
	dw ZapdosAnimationExtra
	dw MoltresAnimationExtra
	dw DratiniAnimationExtra
	dw DragonairAnimationExtra
	dw DragoniteAnimationExtra
	dw ChikoritaAnimationExtra
	dw BayleefAnimationExtra
	dw MeganiumAnimationExtra
	dw CyndaquilAnimationExtra
	dw QuilavaAnimationExtra
	dw TyphlosionAnimationExtra
	dw TotodileAnimationExtra
	dw CroconawAnimationExtra
	dw FeraligatrAnimationExtra
	dw LedybaAnimationExtra
	dw LedianAnimationExtra
	dw CrobatAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw TogepiAnimationExtra
	dw TogeticAnimationExtra
	dw NatuAnimationExtra
	dw XatuAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw BellossomAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw SudowoodoAnimationExtra
	dw PolitoedAnimationExtra
	dw SunkernAnimationExtra
	dw SunfloraAnimationExtra
	dw -1 ; see WooperAnimationExtraPointers
	dw QuagsireAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw MurkrowAnimationExtra
	dw SlowkingAnimationExtra
	dw GirafarigAnimationExtra
	dw PinecoAnimationExtra
	dw ForretressAnimationExtra
	dw GligarAnimationExtra
	dw SteelixAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw ScizorAnimationExtra
	dw HeracrossAnimationExtra
	dw SneaselAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw SlugmaAnimationExtra
	dw MagcargoAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw -1 ; see CorsolaAnimationExtraPointers
	dw SkarmoryAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw PhanpyAnimationExtra
	dw DonphanAnimationExtra
	dw Porygon2AnimationExtra
	dw StantlerAnimationExtra
	dw -1 ; see SmeargleAnimationExtraPointers
	dw ElekidAnimationExtra
	dw MagbyAnimationExtra
	dw MiltankAnimationExtra
	dw BlisseyAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw WingullAnimationExtra
	dw PelipperAnimationExtra
	dw ShroomishAnimationExtra
	dw BreloomAnimationExtra
	dw AronAnimationExtra
	dw LaironAnimationExtra
	dw AggronAnimationExtra
	dw MedititeAnimationExtra
	dw MedichamAnimationExtra
	dw CarvanhaAnimationExtra
	dw SharpedoAnimationExtra
	dw NumelAnimationExtra
	dw CameruptAnimationExtra
	dw CacneaAnimationExtra
	dw CacturneAnimationExtra
	dw SwabluAnimationExtra
	dw AltariaAnimationExtra
	dw SnoruntAnimationExtra
	dw GlalieAnimationExtra
	dw BuizelAnimationExtra
	dw FloatzelAnimationExtra
	dw CherubiAnimationExtra
	dw -1 ; see CherrimAnimationExtraPointers
	dw DrifloonAnimationExtra
	dw DrifblimAnimationExtra
	dw BunearyAnimationExtra
	dw LopunnyAnimationExtra
	dw HonchkrowAnimationExtra
	dw SpiritombAnimationExtra
	dw MunchlaxAnimationExtra
	dw CroagunkAnimationExtra
	dw ToxicroakAnimationExtra
	dw SnoverAnimationExtra
	dw AbomasnowAnimationExtra
	dw WeavileAnimationExtra
	dw MagnezoneAnimationExtra
	dw ElectivireAnimationExtra
	dw MagmortarAnimationExtra
	dw TogekissAnimationExtra
	dw LeafeonAnimationExtra
	dw GlaceonAnimationExtra
	dw GliscorAnimationExtra
	dw MamoswineAnimationExtra
	dw PorygonZAnimationExtra
	dw FroslassAnimationExtra
	dw DrilburAnimationExtra
	dw ExcadrillAnimationExtra
	dw VenipedeAnimationExtra
	dw WhirlipedeAnimationExtra
	dw ScolipedeAnimationExtra
	dw CottoneeAnimationExtra
	dw WhimsicottAnimationExtra
	dw SandileAnimationExtra
	dw KrokorokAnimationExtra
	dw KrookodileAnimationExtra
	dw MaractusAnimationExtra
	dw DwebbleAnimationExtra
	dw CrustleAnimationExtra
	dw ScraggyAnimationExtra
	dw ScraftyAnimationExtra
	dw TirtougaAnimationExtra
	dw CarracostaAnimationExtra
	dw ArchenAnimationExtra
	dw ArcheopsAnimationExtra
	dw MinccinoAnimationExtra
	dw CinccinoAnimationExtra
	dw JoltikAnimationExtra
	dw GalvantulaAnimationExtra
	dw LitwickAnimationExtra
	dw LampentAnimationExtra
	dw ChandelureAnimationExtra
	dw MienfooAnimationExtra
	dw MienshaoAnimationExtra
	dw LarvestaAnimationExtra
	dw VolcaronaAnimationExtra
	dw SylveonAnimationExtra
	dw PhantumpAnimationExtra
	dw TrevenantAnimationExtra
	dw NoibatAnimationExtra
	dw NoivernAnimationExtra
	dw PikipekAnimationExtra
	dw TrumbeakAnimationExtra
	dw ToucannonAnimationExtra
	dw MareanieAnimationExtra
	dw ToxapexAnimationExtra
	dw ComfeyAnimationExtra
	dw -1 ; see MimikyuAnimationExtraPointers
	dw CursolaAnimationExtra
	dw DreepyAnimationExtra
	dw DrakloakAnimationExtra
	dw DragapultAnimationExtra
	dw WyrdeerAnimationExtra
	dw ClodsireAnimationExtra
	dw FarigirafAnimationExtra
	dw BulbasaurAnimationExtra
	dw EggAnimationExtra
