FramesPointers:
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw WeedleFrames
	dw KakunaFrames
	dw BeedrillFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw RattataFrames
	dw RaticateFrames
	dw EkansFrames
	dw ArbokFrames
	dw PikachuFrames
	dw RaichuFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ZubatFrames
	dw GolbatFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw MeowthFrames
	dw PersianFrames
	dw PsyduckFrames
	dw GolduckFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw DoduoFrames
	dw DodrioFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw CuboneFrames
	dw MarowakFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw HorseaFrames
	dw SeadraFrames
	dw StaryuFrames
	dw StarmieFrames
	dw ScytherFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw SnorlaxFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw LedybaFrames
	dw LedianFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw TogepiFrames
	dw TogeticFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingFrames
	dw PinecoFrames
	dw ForretressFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw ScizorFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw CorsolaFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw Porygon2Frames
	dw SmeargleFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw AronFrames
	dw LaironFrames
	dw AggronFrames
	dw MedititeFrames
	dw MedichamFrames
	dw NumelFrames
	dw CameruptFrames
	dw SwabluFrames
	dw AltariaFrames
	dw CorphishFrames
	dw CrawdauntFrames
	dw BuizelFrames
	dw FloatzelFrames
	dw BunearyFrames
	dw LopunnyFrames
	dw HonchkrowFrames
	dw MunchlaxFrames
	dw WeavileFrames
	dw MagnezoneFrames
	dw RhyperiorFrames
	dw ElectivireFrames
	dw MagmortarFrames
	dw TogekissFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw GliscorFrames
	dw MamoswineFrames
	dw PorygonZFrames
	dw CottoneeFrames
	dw WhimsicottFrames
	dw DwebbleFrames
	dw CrustleFrames
	dw JoltikFrames
	dw GalvantulaFrames
	dw LarvestaFrames
	dw VolcaronaFrames
	dw SylveonFrames
	dw NoibatFrames
	dw NoivernFrames
	dw PikipekFrames
	dw TrumbeakFrames
	dw ToucannonFrames
	dw EggFrames
	dw -1 ; unused
