FramesPointers:
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw RattataFrames
	dw RaticateFrames
	dw PikachuFrames
	dw RaichuFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ZubatFrames
	dw GolbatFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw MeowthFrames
	dw PersianFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw DoduoFrames
	dw DodrioFrames
	dw GrimerFrames
	dw MukFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw CuboneFrames
	dw MarowakFrames
	dw KoffingFrames
	dw WeezingFrames
	dw ChanseyFrames
	dw HorseaFrames
	dw SeadraFrames
	dw StaryuFrames
	dw StarmieFrames
	dw ScytherFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw TaurosFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw LedybaFrames
	dw LedianFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw TogepiFrames
	dw TogeticFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingFrames
	dw PinecoFrames
	dw ForretressFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw ScizorFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw CorsolaFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw Porygon2Frames
	dw StantlerFrames
	dw SmeargleFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw WingullFrames
	dw PelipperFrames
	dw RaltsFrames
	dw KirliaFrames
	dw GardevoirFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw AronFrames
	dw LaironFrames
	dw AggronFrames
	dw MedititeFrames
	dw MedichamFrames
	dw CarvanhaFrames
	dw SharpedoFrames
	dw NumelFrames
	dw CameruptFrames
	dw CacneaFrames
	dw CacturneFrames
	dw SwabluFrames
	dw AltariaFrames
	dw SnoruntFrames
	dw GlalieFrames
	dw BuizelFrames
	dw FloatzelFrames
	dw DrifloonFrames
	dw DrifblimFrames
	dw BunearyFrames
	dw LopunnyFrames
	dw HonchkrowFrames
	dw SpiritombFrames
	dw MunchlaxFrames
	dw RioluFrames
	dw LucarioFrames
	dw CroagunkFrames
	dw ToxicroakFrames
	dw SnoverFrames
	dw AbomasnowFrames
	dw WeavileFrames
	dw MagnezoneFrames
	dw ElectivireFrames
	dw MagmortarFrames
	dw TogekissFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw GliscorFrames
	dw MamoswineFrames
	dw PorygonZFrames
	dw GalladeFrames
	dw FroslassFrames
	dw DrilburFrames
	dw ExcadrillFrames
	dw VenipedeFrames
	dw WhirlipedeFrames
	dw ScolipedeFrames
	dw CottoneeFrames
	dw WhimsicottFrames
	dw SandileFrames
	dw KrokorokFrames
	dw KrookodileFrames
	dw MaractusFrames
	dw DwebbleFrames
	dw CrustleFrames
	dw ScraggyFrames
	dw ScraftyFrames
	dw TirtougaFrames
	dw CarracostaFrames
	dw ArchenFrames
	dw ArcheopsFrames
	dw MinccinoFrames
	dw CinccinoFrames
	dw JoltikFrames
	dw GalvantulaFrames
	dw LitwickFrames
	dw LampentFrames
	dw ChandelureFrames
	dw LarvestaFrames
	dw VolcaronaFrames
	dw SylveonFrames
	dw PhantumpFrames
	dw TrevenantFrames
	dw NoibatFrames
	dw NoivernFrames
	dw PikipekFrames
	dw TrumbeakFrames
	dw ToucannonFrames
	dw MareanieFrames
	dw ToxapexFrames
	dw WyrdeerFrames
	dw Raichu_AFrames
	dw ExeggcuteFrames
	dw Exeggutor_AFrames
	dw Marowak_AFrames
	dw Grimer_AFrames
	dw Muk_AFrames
	dw EggFrames
	dw -1 ; unused
