RGB_MONOCHROME_WHITE EQUS "RGB 28, 31, 26"
RGB_MONOCHROME_LIGHT EQUS "RGB 17, 24, 14"
RGB_MONOCHROME_DARK  EQUS "RGB 06, 13, 10"
RGB_MONOCHROME_BLACK EQUS "RGB 01, 03, 04"

PAL_MONOCHROME_WHITE EQU (palred 28 + palgreen 31 + palblue 26)
PAL_MONOCHROME_BLACK EQU (palred 01 + palgreen 03 + palblue 04)


macro MONOCHROME_RGB_FOUR
	RGB_MONOCHROME_WHITE
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
endm

macro MONOCHROME_RGB_FOUR_NIGHT
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
endm

macro MONOCHROME_RGB_FOUR_DARKNESS
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
endm

macro MONOCHROME_RGB_FOUR_OW
	RGB_MONOCHROME_WHITE
	RGB_MONOCHROME_WHITE
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_BLACK
endm

macro MONOCHROME_RGB_FOUR_OW_NIGHT
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
endm

macro MONOCHROME_RGB_FOUR_OW_DARKNESS
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
endm

macro MONOCHROME_RGB_TWO
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
endm

macro MONOCHROME_RGB_TWO_NIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_DARK
endm
