INCLUDE "constants.asm"


SECTION "Overworld Sprites 1", ROMX

CorySpriteGFX::                INCBIN "gfx/sprites/cory.2bpp.lz"
CoryBikeSpriteGFX::            INCBIN "gfx/sprites/cory_bike.2bpp.lz"
CorySurfSpriteGFX::            INCBIN "gfx/sprites/cory_surf.2bpp.lz"
CoryRunSpriteGFX::             INCBIN "gfx/sprites/cory_run.2bpp.lz"
CoryMiscSpriteGFX::            INCBIN "gfx/sprites/cory_misc.2bpp.lz"
CoryBathingSpriteGFX::         INCBIN "gfx/sprites/cory_bathing.2bpp.lz"
CoraSpriteGFX::                INCBIN "gfx/sprites/cora.2bpp.lz"
CoraBikeSpriteGFX::            INCBIN "gfx/sprites/cora_bike.2bpp.lz"
CoraSurfSpriteGFX::            INCBIN "gfx/sprites/cora_surf.2bpp.lz"
CoraRunSpriteGFX::             INCBIN "gfx/sprites/cora_run.2bpp.lz"
CoraMiscSpriteGFX::            INCBIN "gfx/sprites/cora_misc.2bpp.lz"
CoraBathingSpriteGFX::         INCBIN "gfx/sprites/cora_bathing.2bpp.lz"
PippiSpriteGFX::               INCBIN "gfx/sprites/pippi.2bpp.lz"
PippiBikeSpriteGFX::           INCBIN "gfx/sprites/pippi_bike.2bpp.lz"
PippiSurfSpriteGFX::           INCBIN "gfx/sprites/cora_surf.2bpp.lz"
PippiRunSpriteGFX::            INCBIN "gfx/sprites/pippi_run.2bpp.lz"
PippiMiscSpriteGFX::           INCBIN "gfx/sprites/pippi_misc.2bpp.lz"
MomSpriteGFX::                 INCBIN "gfx/sprites/mom.2bpp.lz"
ColbySpriteGFX::               INCBIN "gfx/sprites/colby.2bpp.lz"
StanleySpriteGFX::             INCBIN "gfx/sprites/stanley.2bpp.lz"
RodneySpriteGFX::              INCBIN "gfx/sprites/rodney.2bpp.lz"
WendySpriteGFX:: 	           INCBIN "gfx/sprites/wendy.2bpp.lz"
CharlieSpriteGFX::             INCBIN "gfx/sprites/charlie.2bpp.lz"
PollySpriteGFX::               INCBIN "gfx/sprites/polly.2bpp.lz"
LeilaniSpriteGFX::			   INCBIN "gfx/sprites/leilani.2bpp.lz"
RockySpriteGFX::               INCBIN "gfx/sprites/rocky.2bpp.lz"
DarcySpriteGFX::               INCBIN "gfx/sprites/darcy.2bpp.lz"
Bather1SpriteGFX::             INCBIN "gfx/sprites/bather1.2bpp.lz"
Bather2SpriteGFX::             INCBIN "gfx/sprites/bather2.2bpp.lz"
SteamSpriteGFX::               INCBIN "gfx/sprites/steam.2bpp.lz"
ClownSpriteGFX::               INCBIN "gfx/sprites/clown.2bpp.lz"
SnowGirlSpriteGFX::            INCBIN "gfx/sprites/snowgirl.2bpp.lz"
SnowGirlSmallSpriteGFX::       INCBIN "gfx/sprites/snowgirlsmall.2bpp.lz"
SnowGirlSkateSpriteGFX::       INCBIN "gfx/sprites/snowgirlskate.2bpp.lz"
NidokingMSpriteGFX::      	   INCBIN "gfx/sprites/nidoking_m.2bpp.lz"
NidokingFSpriteGFX::      	   INCBIN "gfx/sprites/nidoking_f.2bpp.lz"
NidokingLeaderSpriteGFX::      INCBIN "gfx/sprites/nidoking_leader.2bpp.lz"
GrimerAOWSpriteGFX::      	   INCBIN "gfx/sprites/grimer_a_ow.2bpp.lz"
BalloonsSpriteGFX::      	   INCBIN "gfx/sprites/balloons.2bpp.lz"
PeepHoleSpriteGFX::      	   INCBIN "gfx/sprites/peep_hole.2bpp.lz"
CasinoSpriteGFX::      	  	   INCBIN "gfx/sprites/casino.2bpp.lz"
CopScrubSpriteGFX::      	   INCBIN "gfx/sprites/cop_scrub.2bpp.lz"


SECTION "Overworld Sprites 2", ROMX

DelinquentMSpriteGFX::         INCBIN "gfx/sprites/delinquentm.2bpp.lz"
DelinquentFSpriteGFX::         INCBIN "gfx/sprites/delinquentf.2bpp.lz"
SpruceSpriteGFX::              INCBIN "gfx/sprites/spruce.2bpp.lz"
InvisibleSpriteGFX::           INCBIN "gfx/sprites/invisible.2bpp.lz"
DodrioRunSpriteGFX::           INCBIN "gfx/sprites/dodriorun.2bpp.lz"
RedsMomSpriteGFX::             INCBIN "gfx/sprites/reds_mom.2bpp.lz"
CoolTrainerFSpriteGFX::        INCBIN "gfx/sprites/cool_trainer_f.2bpp.lz"
CoolTrainerMSpriteGFX::        INCBIN "gfx/sprites/cool_trainer_m.2bpp.lz"
AromaLadySpriteGFX::           INCBIN "gfx/sprites/aroma_lady.2bpp.lz"
ArtistSpriteGFX::              INCBIN "gfx/sprites/artist.2bpp.lz"
BakerSpriteGFX::               INCBIN "gfx/sprites/baker.2bpp.lz"
BattleGirlSpriteGFX::          INCBIN "gfx/sprites/battle_girl.2bpp.lz"
BeautySpriteGFX::              INCBIN "gfx/sprites/beauty.2bpp.lz"
BikerSpriteGFX::               INCBIN "gfx/sprites/biker.2bpp.lz"
BirdKeeperSpriteGFX::          INCBIN "gfx/sprites/bird_keeper.2bpp.lz"
BlackBeltSpriteGFX::           INCBIN "gfx/sprites/black_belt.2bpp.lz"
BoarderSpriteGFX::             INCBIN "gfx/sprites/boarder.2bpp.lz"
BreederSpriteGFX::             INCBIN "gfx/sprites/breeder.2bpp.lz"
BugCatcherSpriteGFX::          INCBIN "gfx/sprites/bug_catcher.2bpp.lz"
BugManiacSpriteGFX::           INCBIN "gfx/sprites/bug_maniac.2bpp.lz"
ScaryPaintingSpriteGFX::       INCBIN "gfx/sprites/scary_painting.2bpp.lz"
MiscConeSpriteGFX::   		   INCBIN "gfx/sprites/misc_cone.2bpp.lz"
JukeboxSpriteGFX::             INCBIN "gfx/sprites/jukebox.2bpp.lz"
LeavesSpriteGFX::              INCBIN "gfx/sprites/leaves.2bpp.lz"
MimikyuDollSpriteGFX::         INCBIN "gfx/sprites/mimikyu_doll.2bpp.lz"
ShroomishOwSpriteGFX::         INCBIN "gfx/icons/shroomish.2bpp.lz"
BreloomOwSpriteGFX::		   INCBIN "gfx/icons/breloom.2bpp.lz"
ChanseyOwSpriteGFX::           INCBIN "gfx/icons/chansey.2bpp.lz"
TuberSpriteGFX::       		   INCBIN "gfx/sprites/tuber.2bpp.lz"
TuberWaterSpriteGFX::          INCBIN "gfx/sprites/tuber_water.2bpp.lz"
ShaolinSpriteGFX::     		   INCBIN "gfx/sprites/shaolin.2bpp.lz"
MasterSpriteGFX::     		   INCBIN "gfx/sprites/master.2bpp.lz"
DittoOwSpriteGFX::       	   INCBIN "gfx/icons/ditto.2bpp.lz"
LedianRangerSpriteGFX::        INCBIN "gfx/sprites/ledian_ranger.2bpp.lz"
LedianRangerFaceSpriteGFX::    INCBIN "gfx/sprites/ledian_ranger_face.2bpp.lz"
LedianRangerPoseSpriteGFX::    INCBIN "gfx/sprites/ledian_ranger_pose.2bpp.lz"
LedianRangerFacePoseSpriteGFX:: INCBIN "gfx/sprites/ledian_ranger_face_pose.2bpp.lz"
RainbowSilverWingSpriteGFX:: 	INCBIN "gfx/sprites/rainbow_silver_wing.2bpp.lz"
ArtifactsSpriteGFX:: 			INCBIN "gfx/sprites/artifacts.2bpp.lz"
CursolaSpriteGFX::         INCBIN "gfx/sprites/cursola.2bpp.lz"
BigCursola1SpriteGFX::         INCBIN "gfx/sprites/big_cursola_1.2bpp.lz"
BigCursola2SpriteGFX::         INCBIN "gfx/sprites/big_cursola_2.2bpp.lz"
ClefairyWalkSpriteGFX::         INCBIN "gfx/sprites/clefairy_walk.2bpp.lz"

SECTION "Overworld Sprites 3", ROMX

BurglarSpriteGFX::             INCBIN "gfx/sprites/burglar.2bpp.lz"
CamperSpriteGFX::              INCBIN "gfx/sprites/camper.2bpp.lz"
ChildSpriteGFX::               INCBIN "gfx/sprites/child.2bpp.lz"
CoolDudeSpriteGFX::            INCBIN "gfx/sprites/cool_dude.2bpp.lz"
CosplayerSpriteGFX::           INCBIN "gfx/sprites/cosplayer.2bpp.lz"
CowgirlSpriteGFX::             INCBIN "gfx/sprites/cowgirl.2bpp.lz"
CuteGirlSpriteGFX::            INCBIN "gfx/sprites/cute_girl.2bpp.lz"
DragonTamerSpriteGFX::         INCBIN "gfx/sprites/dragon_tamer.2bpp.lz"
ElderSpriteGFX::               INCBIN "gfx/sprites/elder.2bpp.lz"
EngineerSpriteGFX::            INCBIN "gfx/sprites/engineer.2bpp.lz"
FatGuySpriteGFX::              INCBIN "gfx/sprites/fat_guy.2bpp.lz"
FirebreatherSpriteGFX::        INCBIN "gfx/sprites/firebreather.2bpp.lz"
FisherSpriteGFX::              INCBIN "gfx/sprites/fisher.2bpp.lz"
GentlemanSpriteGFX::           INCBIN "gfx/sprites/gentleman.2bpp.lz"
GrampsSpriteGFX::              INCBIN "gfx/sprites/gramps.2bpp.lz"
GrannySpriteGFX::              INCBIN "gfx/sprites/granny.2bpp.lz"
HexManiacSpriteGFX::           INCBIN "gfx/sprites/hex_maniac.2bpp.lz"
HikerSpriteGFX::               INCBIN "gfx/sprites/hiker.2bpp.lz"
JugglerSpriteGFX::             INCBIN "gfx/sprites/juggler.2bpp.lz"
KimonoGirlSpriteGFX::          INCBIN "gfx/sprites/kimono_girl.2bpp.lz"
MinaSpriteGFX::  		       INCBIN "gfx/sprites/mina.2bpp.lz"
MinaGroundSpriteGFX::  		   INCBIN "gfx/sprites/mina_ground.2bpp.lz"
DisguiseMasterGFX::			   INCBIN "gfx/sprites/disguise_master.2bpp.lz"
CoryPhoto1SpriteGFX::          INCBIN "gfx/sprites/cory_photo_1.2bpp.lz"
CoryPhoto2SpriteGFX::          INCBIN "gfx/sprites/cory_photo_2.2bpp.lz"
CoryPhoto3SpriteGFX::          INCBIN "gfx/sprites/cory_photo_3.2bpp.lz"
CoryPhoto4SpriteGFX::          INCBIN "gfx/sprites/cory_photo_4.2bpp.lz"
CoraPhoto1SpriteGFX::          INCBIN "gfx/sprites/cora_photo_1.2bpp.lz"
CoraPhoto2SpriteGFX::          INCBIN "gfx/sprites/cora_photo_2.2bpp.lz"
CoraPhoto3SpriteGFX::          INCBIN "gfx/sprites/cora_photo_3.2bpp.lz"
CoraPhoto4SpriteGFX::          INCBIN "gfx/sprites/cora_photo_4.2bpp.lz"
PicnicSpriteGFX::         	   INCBIN "gfx/sprites/picnic.2bpp.lz"


SECTION "Overworld Sprites 4", ROMX

LadySpriteGFX::                INCBIN "gfx/sprites/lady.2bpp.lz"
LassSpriteGFX::                INCBIN "gfx/sprites/lass.2bpp.lz"
MatronSpriteGFX::              INCBIN "gfx/sprites/matron.2bpp.lz"
NurseSpriteGFX::               INCBIN "gfx/sprites/nurse.2bpp.lz"
OfficerSpriteGFX::             INCBIN "gfx/sprites/officer.2bpp.lz"
OfficerFSpriteGFX::            INCBIN "gfx/sprites/officer_f.2bpp.lz"
PharmacistSpriteGFX::          INCBIN "gfx/sprites/pharmacist.2bpp.lz"
PISpriteGFX::                  INCBIN "gfx/sprites/pi.2bpp.lz"
PicnickerSpriteGFX::           INCBIN "gfx/sprites/picnicker.2bpp.lz"
PokefanMSpriteGFX::            INCBIN "gfx/sprites/pokefan_m.2bpp.lz"
PokefanFSpriteGFX::            INCBIN "gfx/sprites/pokefan_f.2bpp.lz"
PokemaniacSpriteGFX::          INCBIN "gfx/sprites/pokemaniac.2bpp.lz"
PsychicSpriteGFX::             INCBIN "gfx/sprites/psychic.2bpp.lz"
RichBoySpriteGFX::             INCBIN "gfx/sprites/rich_boy.2bpp.lz"
RockerSpriteGFX::              INCBIN "gfx/sprites/rocker.2bpp.lz"
SnareSpriteGFX::               INCBIN "gfx/sprites/snare.2bpp.lz"
SnareGirlSpriteGFX::           INCBIN "gfx/sprites/snare_girl.2bpp.lz"
SnareWaterSpriteGFX::		   INCBIN "gfx/sprites/snare_water.2bpp.lz"
KageSpriteGFX::				   INCBIN "gfx/sprites/kage.2bpp.lz"
KageWaterSpriteGFX::		   INCBIN "gfx/sprites/kage_water.2bpp.lz"
LockeSpriteGFX::			   INCBIN "gfx/sprites/locke.2bpp.lz"
CueballSpriteGFX::             INCBIN "gfx/sprites/cue_ball.2bpp.lz"
SageSpriteGFX::                INCBIN "gfx/sprites/sage.2bpp.lz"
SailorSpriteGFX::              INCBIN "gfx/sprites/sailor.2bpp.lz"
TrunksWaterSpriteGFX::		   INCBIN "gfx/sprites/trunks_water.2bpp.lz"
PaintingsSpriteGFX::		   INCBIN "gfx/sprites/paintings.2bpp.lz"
CoralStarSpriteGFX::		   INCBIN "gfx/sprites/coral_star.2bpp.lz"


SECTION "Overworld Sprites 5", ROMX

SchoolboySpriteGFX::           INCBIN "gfx/sprites/schoolboy.2bpp.lz"
SchoolgirlSpriteGFX::          INCBIN "gfx/sprites/schoolgirl.2bpp.lz"
ScientistSpriteGFX::           INCBIN "gfx/sprites/scientist.2bpp.lz"
ScientistFSpriteGFX::          INCBIN "gfx/sprites/scientist_f.2bpp.lz"
SightseerMSpriteGFX::          INCBIN "gfx/sprites/sightseer_m.2bpp.lz"
SkierSpriteGFX::               INCBIN "gfx/sprites/skier.2bpp.lz"
SuperNerdSpriteGFX::           INCBIN "gfx/sprites/super_nerd.2bpp.lz"
SwimmerGirlSpriteGFX::         INCBIN "gfx/sprites/swimmer_f.2bpp.lz"
SwimmerGuySpriteGFX::          INCBIN "gfx/sprites/swimmer_m.2bpp.lz"
TamerSpriteGFX::               INCBIN "gfx/sprites/tamer.2bpp.lz"
TeacherSpriteGFX::             INCBIN "gfx/sprites/teacher.2bpp.lz"
TwinSpriteGFX::                INCBIN "gfx/sprites/twin.2bpp.lz"
VeteranMSpriteGFX::            INCBIN "gfx/sprites/veteran_m.2bpp.lz"
VeteranFSpriteGFX::            INCBIN "gfx/sprites/veteran_f.2bpp.lz"
WaitressSpriteGFX::            INCBIN "gfx/sprites/waitress.2bpp.lz"
YoungsterSpriteGFX::           INCBIN "gfx/sprites/youngster.2bpp.lz"
BowingNurseSpriteGFX::         INCBIN "gfx/sprites/bowing_nurse.2bpp.lz"
ClerkSpriteGFX::               INCBIN "gfx/sprites/clerk.2bpp.lz"
ReceptionistSpriteGFX::        INCBIN "gfx/sprites/receptionist.2bpp.lz"
LinkReceptionistSpriteGFX::    INCBIN "gfx/sprites/link_receptionist.2bpp.lz"
SwimmerGirlLandSpriteGFX::     INCBIN "gfx/sprites/swimmer_f_land.2bpp.lz"
MuseumStandeeSpriteGFX::       INCBIN "gfx/sprites/museum_standee.2bpp.lz"


SECTION "Overworld Sprites 6", ROMX

GymGuySpriteGFX::              INCBIN "gfx/sprites/gym_guy.2bpp.lz"
MallCopSpriteGFX::             INCBIN "gfx/sprites/mall_cop.2bpp.lz"
FishingGuruSpriteGFX::         INCBIN "gfx/sprites/fishing_guru.2bpp.lz"
GameboyKidSpriteGFX::          INCBIN "gfx/sprites/gameboy_kid.2bpp.lz"
GamerGirlSpriteGFX::           INCBIN "gfx/sprites/gamer_girl.2bpp.lz"
PatchesSpriteGFX::		       INCBIN "gfx/sprites/patches.2bpp.lz"
PatchesFallSpriteGFX::	       INCBIN "gfx/sprites/patches_fall.2bpp.lz"
SafariOfficerSpriteGFX::       INCBIN "gfx/sprites/safari_officer.2bpp.lz"
ReporterSpriteGFX::     	   INCBIN "gfx/sprites/reporter.2bpp.lz"
CameramanSpriteGFX::    	   INCBIN "gfx/sprites/cameraman.2bpp.lz"
SurfingPikachuSpriteGFX::      INCBIN "gfx/sprites/surf_pikachu.2bpp.lz"
BigSnorlaxSpriteGFX::          INCBIN "gfx/sprites/big_snorlax.2bpp.lz"
BigOnixSpriteGFX::    	       INCBIN "gfx/sprites/big_onix.2bpp.lz"
BigLaprasSpriteGFX::           INCBIN "gfx/sprites/big_lapras.2bpp.lz"
BigMukSpriteGFX::              INCBIN "gfx/sprites/big_muk.2bpp.lz"
BigGyaradosSpriteGFX::         INCBIN "gfx/sprites/big_gyarados.2bpp.lz"
SlowpoketailSpriteGFX::        INCBIN "gfx/sprites/slowpoketail.2bpp.lz"
WeirdTreeSpriteGFX::           INCBIN "gfx/sprites/weird_tree.2bpp.lz"
BallCutFruitSpriteGFX::        INCBIN "gfx/sprites/ball_cut_fruit.2bpp.lz"
BoulderRockFossilSpriteGFX::   INCBIN "gfx/sprites/boulder_rock_fossil.2bpp.lz"
BookPaperPokedexSpriteGFX::    INCBIN "gfx/sprites/book_paper_pokedex.2bpp.lz"
SnesSpriteGFX::                INCBIN "gfx/sprites/snes.2bpp.lz"
N64SpriteGFX::                 INCBIN "gfx/sprites/n64.2bpp.lz"
SunbeamViewSpriteGFX::         INCBIN "gfx/sprites/sunbeam_view.2bpp.lz"
SunbeamViewSpriteCloudsGFX::   INCBIN "gfx/sprites/sunbeam_view_clouds.2bpp.lz"
ChefSpriteGFX::  			   INCBIN "gfx/sprites/chef.2bpp.lz"


SECTION "Overworld Sprites 7", ROMX

GameCubeSpriteGFX::            INCBIN "gfx/sprites/gamecube.2bpp.lz"
CandleSpriteGFX::        	   INCBIN "gfx/sprites/candle.2bpp.lz"
GoldTrophySpriteGFX::          INCBIN "gfx/sprites/gold_trophy.2bpp.lz"
SailboatSpriteGFX::            INCBIN "gfx/sprites/sailboat.2bpp.lz"
MiscOverheadSpriteGFX::        INCBIN "gfx/sprites/misc_overhead.2bpp.lz"
SunbatherSpriteGFX::       	   INCBIN "gfx/sprites/sunbather.2bpp.lz"
UmbrellaSpriteGFX::			   INCBIN "gfx/sprites/umbrella.2bpp.lz"
Bikini1SpriteGFX::             INCBIN "gfx/sprites/bikini1.2bpp.lz"
Bikini2SpriteGFX::             INCBIN "gfx/sprites/bikini2.2bpp.lz"
Bikini3SpriteGFX::             INCBIN "gfx/sprites/bikini3.2bpp.lz"
TrunksSpriteGFX::			   INCBIN "gfx/sprites/trunks.2bpp.lz"
SittingYoungsterGFX::          INCBIN "gfx/sprites/sitting_youngster.2bpp.lz"
SittingBirdKeeperGFX::         INCBIN "gfx/sprites/sitting_birdkeeper.2bpp.lz"
SittingGuyGFX::                INCBIN "gfx/sprites/sitting_guy.2bpp.lz"
SittingGentlemanGFX::          INCBIN "gfx/sprites/sitting_gentleman.2bpp.lz"
SittingTwinGFX::               INCBIN "gfx/sprites/sitting_twin.2bpp.lz"
SittingPonytailGFX::           INCBIN "gfx/sprites/sitting_ponytail.2bpp.lz"
SittingPokeFanGFX::            INCBIN "gfx/sprites/sitting_pokefan.2bpp.lz"
SittingLadyGFX::               INCBIN "gfx/sprites/sitting_lady.2bpp.lz"
MallSignGFX::              	   INCBIN "gfx/sprites/mall_sign.2bpp.lz"
CampfireGFX::              	   INCBIN "gfx/sprites/campfire.2bpp.lz"
Valve1GFX::					   INCBIN "gfx/sprites/valve1.2bpp.lz"
Valve2GFX::					   INCBIN "gfx/sprites/valve2.2bpp.lz"
PlankBridgeGFX::			   INCBIN "gfx/sprites/plankbridge.2bpp.lz"
PlankBridge2GFX::			   INCBIN "gfx/sprites/plankbridge2.2bpp.lz"
TrafficLightGFX::			   INCBIN "gfx/sprites/traffic_light.2bpp.lz"
HangarPartsGFX::			   INCBIN "gfx/sprites/hangar_parts.2bpp.lz"
KoffingBeanGFX::			   INCBIN "gfx/sprites/koffing_bean.2bpp.lz"
ClothesRacksGFX::			   INCBIN "gfx/sprites/clothes_racks.2bpp.lz"
MiscBaggageGFX::			   INCBIN "gfx/sprites/misc_baggage.2bpp.lz"
BigMamoswineSpriteGFX::        INCBIN "gfx/sprites/big_mamoswine.2bpp.lz"
LighthouseSpriteGFX::      	   INCBIN "gfx/sprites/lighthouse.2bpp.lz"
FrankieSpriteGFX::             INCBIN "gfx/sprites/frankie.2bpp.lz"
SkaterSpriteGFX::              INCBIN "gfx/sprites/skater.2bpp.lz"
SpaWorkerSpriteGFX::           INCBIN "gfx/sprites/spa_worker.2bpp.lz"
SpaTrainerSpriteGFX::          INCBIN "gfx/sprites/spa_trainer.2bpp.lz"
PorygonScreenGFX::			   INCBIN "gfx/sprites/porygon_screen.2bpp.lz"


SECTION "Overworld Sprites 8", ROMX

RedSpriteGFX::           	   INCBIN "gfx/sprites/red.2bpp.lz"
RedBikeSpriteGFX::       	   INCBIN "gfx/sprites/red_bike.2bpp.lz"
RedSurfSpriteGFX::       	   INCBIN "gfx/sprites/red_surf.2bpp.lz"
RedRunSpriteGFX::              INCBIN "gfx/sprites/red_run.2bpp.lz"
RedMiscSpriteGFX::             INCBIN "gfx/sprites/red_misc.2bpp.lz"
LeafSpriteGFX::                INCBIN "gfx/sprites/pippi.2bpp.lz"
LeafBikeSpriteGFX::            INCBIN "gfx/sprites/pippi_bike.2bpp.lz"
LeafSurfSpriteGFX::            INCBIN "gfx/sprites/cora_surf.2bpp.lz"
LeafRunSpriteGFX::             INCBIN "gfx/sprites/pippi_run.2bpp.lz"
LeafMiscSpriteGFX::            INCBIN "gfx/sprites/pippi_misc.2bpp.lz"
GoldSpriteGFX::                INCBIN "gfx/sprites/pippi.2bpp.lz"
GoldBikeSpriteGFX::            INCBIN "gfx/sprites/pippi_bike.2bpp.lz"
GoldSurfSpriteGFX::            INCBIN "gfx/sprites/cora_surf.2bpp.lz"
GoldRunSpriteGFX::             INCBIN "gfx/sprites/pippi_run.2bpp.lz"
GoldMiscSpriteGFX::            INCBIN "gfx/sprites/pippi_misc.2bpp.lz"
KrisSpriteGFX::                INCBIN "gfx/sprites/pippi.2bpp.lz"
KrisBikeSpriteGFX::            INCBIN "gfx/sprites/pippi_bike.2bpp.lz"
KrisSurfSpriteGFX::            INCBIN "gfx/sprites/cora_surf.2bpp.lz"
KrisRunSpriteGFX::             INCBIN "gfx/sprites/pippi_run.2bpp.lz"
KrisMiscSpriteGFX::            INCBIN "gfx/sprites/pippi_misc.2bpp.lz"
CorySkateboardSpriteGFX::	   INCBIN "gfx/sprites/cory_skateboard.2bpp.lz"
CoraSkateboardSpriteGFX::	   INCBIN "gfx/sprites/cora_skateboard.2bpp.lz"
PippiSkateboardSpriteGFX::	   INCBIN "gfx/sprites/pippi_skateboard.2bpp.lz"
RedSkateboardSpriteGFX::	   INCBIN "gfx/sprites/red_skateboard.2bpp.lz"
LeafSkateboardSpriteGFX::	   INCBIN "gfx/sprites/leaf_skateboard.2bpp.lz"
GoldSkateboardSpriteGFX::	   INCBIN "gfx/sprites/gold_skateboard.2bpp.lz"
KrisSkateboardSpriteGFX::	   INCBIN "gfx/sprites/kris_skateboard.2bpp.lz"
CorySkateboard2SpriteGFX::	   INCBIN "gfx/sprites/cory_skateboard_2.2bpp.lz"
CoraSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/cora_skateboard_2.2bpp.lz"
PippiSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/pippi_skateboard_2.2bpp.lz"
RedSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/red_skateboard_2.2bpp.lz"
LeafSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/leaf_skateboard_2.2bpp.lz"
GoldSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/gold_skateboard_2.2bpp.lz"
KrisSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/kris_skateboard_2.2bpp.lz"

SECTION "Overworld Sprites 9", ROMX

CorySkateboardGrindingSpriteGFX::		INCBIN "gfx/sprites/cory_skateboard_grinding.2bpp.lz"
CorySkateboardFallingSpriteGFX::		INCBIN "gfx/sprites/cory_skateboard_falling.2bpp.lz"
CoraSkateboardGrindingSpriteGFX::		INCBIN "gfx/sprites/cora_skateboard_grinding.2bpp.lz"
CoraSkateboardFallingSpriteGFX::		INCBIN "gfx/sprites/cora_skateboard_falling.2bpp.lz"
PippiSkateboardGrindingSpriteGFX::		INCBIN "gfx/sprites/pippi_skateboard_grinding.2bpp.lz"
RedSkateboardGrindingSpriteGFX::		INCBIN "gfx/sprites/red_skateboard_grinding.2bpp.lz"
LeafSkateboardGrindingSpriteGFX::		INCBIN "gfx/sprites/leaf_skateboard_grinding.2bpp.lz"
GoldSkateboardGrindingSpriteGFX::		INCBIN "gfx/sprites/gold_skateboard_grinding.2bpp.lz"
KrisSkateboardGrindingSpriteGFX::		INCBIN "gfx/sprites/kris_skateboard_grinding.2bpp.lz"
MaractusGraffitiSpriteGFX::				INCBIN "gfx/sprites/maractus_graffiti.2bpp.lz"
SingerSpriteGFX::						INCBIN "gfx/sprites/singer.2bpp.lz"
DaisySpriteGFX::						INCBIN "gfx/sprites/daisy.2bpp.lz"
ErikaSpriteGFX::						INCBIN "gfx/sprites/erika.2bpp.lz"
LeilaniBedSpriteGFX::					INCBIN "gfx/sprites/leilani_bed.2bpp.lz"
PigtailsSpriteGFX::						INCBIN "gfx/sprites/pigtails.2bpp.lz"
LeilaniChairSpriteGFX::					INCBIN "gfx/sprites/leilani_chair.2bpp.lz"
LeilaniChair2SpriteGFX::				INCBIN "gfx/sprites/leilani_chair2.2bpp.lz"
CoryDiveSpriteGFX::						INCBIN "gfx/sprites/cory_dive.2bpp.lz"
CoraDiveSpriteGFX::						INCBIN "gfx/sprites/cora_dive.2bpp.lz"
