INCLUDE "constants.asm"


SECTION "Overworld Sprites 1", ROMX

CorySpriteGFX::                INCBIN "gfx/sprites/cory.2bpp"
CoryBikeSpriteGFX::            INCBIN "gfx/sprites/cory_bike.2bpp"
CorySurfSpriteGFX::            INCBIN "gfx/sprites/cory_surf.2bpp"
CoryRunSpriteGFX::             INCBIN "gfx/sprites/cory_run.2bpp"
CoryMiscSpriteGFX::            INCBIN "gfx/sprites/cory_misc.2bpp"
CoryBathingSpriteGFX::         INCBIN "gfx/sprites/cory_bathing.2bpp"
CoraSpriteGFX::                INCBIN "gfx/sprites/cora.2bpp"
CoraBikeSpriteGFX::            INCBIN "gfx/sprites/cora_bike.2bpp"
CoraSurfSpriteGFX::            INCBIN "gfx/sprites/cora_surf.2bpp"
CoraRunSpriteGFX::             INCBIN "gfx/sprites/cora_run.2bpp"
CoraMiscSpriteGFX::            INCBIN "gfx/sprites/cora_misc.2bpp"
CoraBathingSpriteGFX::         INCBIN "gfx/sprites/cora_bathing.2bpp"
PippiSpriteGFX::               INCBIN "gfx/sprites/pippi.2bpp"
PippiBikeSpriteGFX::           INCBIN "gfx/sprites/pippi_bike.2bpp"
PippiSurfSpriteGFX::           INCBIN "gfx/sprites/cora_surf.2bpp"
PippiRunSpriteGFX::            INCBIN "gfx/sprites/pippi_run.2bpp"
PippiMiscSpriteGFX::           INCBIN "gfx/sprites/pippi_misc.2bpp"
MomSpriteGFX::                 INCBIN "gfx/sprites/mom.2bpp"
ColbySpriteGFX::               INCBIN "gfx/sprites/colby.2bpp"
StanleySpriteGFX::             INCBIN "gfx/sprites/stanley.2bpp"
RodneySpriteGFX::              INCBIN "gfx/sprites/rodney.2bpp"
WendySpriteGFX:: 	           INCBIN "gfx/sprites/wendy.2bpp"
CharlieSpriteGFX::             INCBIN "gfx/sprites/charlie.2bpp"
ChuckSpriteGFX::               INCBIN "gfx/sprites/chuck.2bpp"
JasmineSpriteGFX::             INCBIN "gfx/sprites/jasmine.2bpp"
PryceSpriteGFX::               INCBIN "gfx/sprites/pryce.2bpp"
ClairSpriteGFX::               INCBIN "gfx/sprites/clair.2bpp"
Bather1SpriteGFX::             INCBIN "gfx/sprites/bather1.2bpp"
Bather2SpriteGFX::             INCBIN "gfx/sprites/bather2.2bpp"
SteamSpriteGFX::               INCBIN "gfx/sprites/steam.2bpp"
ClownSpriteGFX::               INCBIN "gfx/sprites/clown.2bpp"
SnowGirlSpriteGFX::            INCBIN "gfx/sprites/snowgirl.2bpp"
SnowGirlSmallSpriteGFX::       INCBIN "gfx/sprites/snowgirlsmall.2bpp"
SnowGirlSkateSpriteGFX::       INCBIN "gfx/sprites/snowgirlskate.2bpp"
NidokingMSpriteGFX::      	   INCBIN "gfx/sprites/nidoking_m.2bpp"
NidokingFSpriteGFX::      	   INCBIN "gfx/sprites/nidoking_f.2bpp"
NidokingLeaderSpriteGFX::      INCBIN "gfx/sprites/nidoking_leader.2bpp"
GrimerAOWSpriteGFX::      	   INCBIN "gfx/sprites/grimer_a_ow.2bpp"
BalloonsSpriteGFX::      	   INCBIN "gfx/sprites/balloons.2bpp"
PeepHoleSpriteGFX::      	   INCBIN "gfx/sprites/peep_hole.2bpp"
CasinoSpriteGFX::      	  	   INCBIN "gfx/sprites/casino.2bpp"


SECTION "Overworld Sprites 2", ROMX

DelinquentMSpriteGFX::         INCBIN "gfx/sprites/delinquentm.2bpp"
DelinquentFSpriteGFX::         INCBIN "gfx/sprites/delinquentf.2bpp"
SpruceSpriteGFX::              INCBIN "gfx/sprites/spruce.2bpp"
InvisibleSpriteGFX::           INCBIN "gfx/sprites/invisible.2bpp"
DodrioRunSpriteGFX::           INCBIN "gfx/sprites/dodriorun.2bpp"
RedsMomSpriteGFX::             INCBIN "gfx/sprites/reds_mom.2bpp"
CoolTrainerFSpriteGFX::        INCBIN "gfx/sprites/cool_trainer_f.2bpp"
CoolTrainerMSpriteGFX::        INCBIN "gfx/sprites/cool_trainer_m.2bpp"
AromaLadySpriteGFX::           INCBIN "gfx/sprites/aroma_lady.2bpp"
ArtistSpriteGFX::              INCBIN "gfx/sprites/artist.2bpp"
BakerSpriteGFX::               INCBIN "gfx/sprites/baker.2bpp"
BattleGirlSpriteGFX::          INCBIN "gfx/sprites/battle_girl.2bpp"
BeautySpriteGFX::              INCBIN "gfx/sprites/beauty.2bpp"
BikerSpriteGFX::               INCBIN "gfx/sprites/biker.2bpp"
BirdKeeperSpriteGFX::          INCBIN "gfx/sprites/bird_keeper.2bpp"
BlackBeltSpriteGFX::           INCBIN "gfx/sprites/black_belt.2bpp"
BoarderSpriteGFX::             INCBIN "gfx/sprites/boarder.2bpp"
BreederSpriteGFX::             INCBIN "gfx/sprites/breeder.2bpp"
BugCatcherSpriteGFX::          INCBIN "gfx/sprites/bug_catcher.2bpp"
BugManiacSpriteGFX::           INCBIN "gfx/sprites/bug_maniac.2bpp"


SECTION "Overworld Sprites 3", ROMX

BurglarSpriteGFX::             INCBIN "gfx/sprites/burglar.2bpp"
CamperSpriteGFX::              INCBIN "gfx/sprites/camper.2bpp"
ChildSpriteGFX::               INCBIN "gfx/sprites/child.2bpp"
CoolDudeSpriteGFX::            INCBIN "gfx/sprites/cool_dude.2bpp"
CosplayerSpriteGFX::           INCBIN "gfx/sprites/cosplayer.2bpp"
CowgirlSpriteGFX::             INCBIN "gfx/sprites/cowgirl.2bpp"
CuteGirlSpriteGFX::            INCBIN "gfx/sprites/cute_girl.2bpp"
DragonTamerSpriteGFX::         INCBIN "gfx/sprites/dragon_tamer.2bpp"
ElderSpriteGFX::               INCBIN "gfx/sprites/elder.2bpp"
EngineerSpriteGFX::            INCBIN "gfx/sprites/engineer.2bpp"
FatGuySpriteGFX::              INCBIN "gfx/sprites/fat_guy.2bpp"
FirebreatherSpriteGFX::        INCBIN "gfx/sprites/firebreather.2bpp"
FisherSpriteGFX::              INCBIN "gfx/sprites/fisher.2bpp"
GentlemanSpriteGFX::           INCBIN "gfx/sprites/gentleman.2bpp"
GrampsSpriteGFX::              INCBIN "gfx/sprites/gramps.2bpp"
GrannySpriteGFX::              INCBIN "gfx/sprites/granny.2bpp"
HexManiacSpriteGFX::           INCBIN "gfx/sprites/hex_maniac.2bpp"
HikerSpriteGFX::               INCBIN "gfx/sprites/hiker.2bpp"
JugglerSpriteGFX::             INCBIN "gfx/sprites/juggler.2bpp"
KimonoGirlSpriteGFX::          INCBIN "gfx/sprites/kimono_girl.2bpp"


SECTION "Overworld Sprites 4", ROMX

LadySpriteGFX::                INCBIN "gfx/sprites/lady.2bpp"
LassSpriteGFX::                INCBIN "gfx/sprites/lass.2bpp"
MatronSpriteGFX::              INCBIN "gfx/sprites/matron.2bpp"
NurseSpriteGFX::               INCBIN "gfx/sprites/nurse.2bpp"
OfficerSpriteGFX::             INCBIN "gfx/sprites/officer.2bpp"
OfficerFSpriteGFX::            INCBIN "gfx/sprites/officer_f.2bpp"
PharmacistSpriteGFX::          INCBIN "gfx/sprites/pharmacist.2bpp"
PISpriteGFX::                  INCBIN "gfx/sprites/pi.2bpp"
PicnickerSpriteGFX::           INCBIN "gfx/sprites/picnicker.2bpp"
PokefanMSpriteGFX::            INCBIN "gfx/sprites/pokefan_m.2bpp"
PokefanFSpriteGFX::            INCBIN "gfx/sprites/pokefan_f.2bpp"
PokemaniacSpriteGFX::          INCBIN "gfx/sprites/pokemaniac.2bpp"
PsychicSpriteGFX::             INCBIN "gfx/sprites/psychic.2bpp"
RichBoySpriteGFX::             INCBIN "gfx/sprites/rich_boy.2bpp"
RockerSpriteGFX::              INCBIN "gfx/sprites/rocker.2bpp"
SnareSpriteGFX::               INCBIN "gfx/sprites/snare.2bpp"
SnareGirlSpriteGFX::           INCBIN "gfx/sprites/snare_girl.2bpp"
SnareWaterSpriteGFX::		   INCBIN "gfx/sprites/snare_water.2bpp"
KageSpriteGFX::				   INCBIN "gfx/sprites/kage.2bpp"
KageWaterSpriteGFX::		   INCBIN "gfx/sprites/kage_water.2bpp"
LockeSpriteGFX::			   INCBIN "gfx/sprites/locke.2bpp"
RoughneckSpriteGFX::           INCBIN "gfx/sprites/roughneck.2bpp"
SageSpriteGFX::                INCBIN "gfx/sprites/sage.2bpp"
SailorSpriteGFX::              INCBIN "gfx/sprites/sailor.2bpp"


SECTION "Overworld Sprites 5", ROMX

SchoolboySpriteGFX::           INCBIN "gfx/sprites/schoolboy.2bpp"
SchoolgirlSpriteGFX::          INCBIN "gfx/sprites/schoolgirl.2bpp"
ScientistSpriteGFX::           INCBIN "gfx/sprites/scientist.2bpp"
ScientistFSpriteGFX::          INCBIN "gfx/sprites/scientist_f.2bpp"
SightseerMSpriteGFX::          INCBIN "gfx/sprites/sightseer_m.2bpp"
SkierSpriteGFX::               INCBIN "gfx/sprites/skier.2bpp"
SuperNerdSpriteGFX::           INCBIN "gfx/sprites/super_nerd.2bpp"
SwimmerGirlSpriteGFX::         INCBIN "gfx/sprites/swimmer_f.2bpp"
SwimmerGuySpriteGFX::          INCBIN "gfx/sprites/swimmer_m.2bpp"
TamerSpriteGFX::               INCBIN "gfx/sprites/tamer.2bpp"
TeacherSpriteGFX::             INCBIN "gfx/sprites/teacher.2bpp"
TwinSpriteGFX::                INCBIN "gfx/sprites/twin.2bpp"
VeteranMSpriteGFX::            INCBIN "gfx/sprites/veteran_m.2bpp"
VeteranFSpriteGFX::            INCBIN "gfx/sprites/veteran_f.2bpp"
WaitressSpriteGFX::            INCBIN "gfx/sprites/waitress.2bpp"
YoungsterSpriteGFX::           INCBIN "gfx/sprites/youngster.2bpp"
BowingNurseSpriteGFX::         INCBIN "gfx/sprites/bowing_nurse.2bpp"
ClerkSpriteGFX::               INCBIN "gfx/sprites/clerk.2bpp"
ReceptionistSpriteGFX::        INCBIN "gfx/sprites/receptionist.2bpp"
LinkReceptionistSpriteGFX::    INCBIN "gfx/sprites/link_receptionist.2bpp"


SECTION "Overworld Sprites 6", ROMX

GymGuySpriteGFX::              INCBIN "gfx/sprites/gym_guy.2bpp"
FishingGuruSpriteGFX::         INCBIN "gfx/sprites/fishing_guru.2bpp"
GameboyKidSpriteGFX::          INCBIN "gfx/sprites/gameboy_kid.2bpp"
GamerGirlSpriteGFX::           INCBIN "gfx/sprites/gamer_girl.2bpp"
SilphEmployeeSpriteGFX::       INCBIN "gfx/sprites/silph_employee.2bpp"
SafariOfficerSpriteGFX::       INCBIN "gfx/sprites/safari_officer.2bpp"
ReporterSpriteGFX::     	   INCBIN "gfx/sprites/reporter.2bpp"
CameramanSpriteGFX::    	   INCBIN "gfx/sprites/cameraman.2bpp"
SurfingPikachuSpriteGFX::      INCBIN "gfx/sprites/surf_pikachu.2bpp"
BigSnorlaxSpriteGFX::          INCBIN "gfx/sprites/big_snorlax.2bpp"
BigLaprasSpriteGFX::           INCBIN "gfx/sprites/big_lapras.2bpp"
BigMukSpriteGFX::              INCBIN "gfx/sprites/big_muk.2bpp"
BigGyaradosSpriteGFX::         INCBIN "gfx/sprites/big_gyarados.2bpp"
SlowpoketailSpriteGFX::        INCBIN "gfx/sprites/slowpoketail.2bpp"
WeirdTreeSpriteGFX::           INCBIN "gfx/sprites/weird_tree.2bpp"
BallCutFruitSpriteGFX::        INCBIN "gfx/sprites/ball_cut_fruit.2bpp"
BoulderRockFossilSpriteGFX::   INCBIN "gfx/sprites/boulder_rock_fossil.2bpp"
BookPaperPokedexSpriteGFX::    INCBIN "gfx/sprites/book_paper_pokedex.2bpp"
SnesSpriteGFX::                INCBIN "gfx/sprites/snes.2bpp"
N64SpriteGFX::                 INCBIN "gfx/sprites/n64.2bpp"
SunbeamViewSpriteGFX::         INCBIN "gfx/sprites/sunbeam_view.2bpp"
SunbeamViewSpriteCloudsGFX::   INCBIN "gfx/sprites/sunbeam_view_clouds.2bpp"


SECTION "Overworld Sprites 7", ROMX

GameCubeSpriteGFX::            INCBIN "gfx/sprites/gamecube.2bpp"
CandleSpriteGFX::        	   INCBIN "gfx/sprites/candle.2bpp"
GoldTrophySpriteGFX::          INCBIN "gfx/sprites/gold_trophy.2bpp"
SailboatSpriteGFX::            INCBIN "gfx/sprites/sailboat.2bpp"
MiscOverheadSpriteGFX::        INCBIN "gfx/sprites/misc_overhead.2bpp"
RowboatSpriteGFX::       	   INCBIN "gfx/sprites/rowboat.2bpp"
UmbrellaSpriteGFX::			   INCBIN "gfx/sprites/umbrella.2bpp"
Bikini1SpriteGFX::             INCBIN "gfx/sprites/bikini1.2bpp"
Bikini2SpriteGFX::             INCBIN "gfx/sprites/bikini2.2bpp"
Bikini3SpriteGFX::             INCBIN "gfx/sprites/bikini3.2bpp"
TrunksSpriteGFX::			   INCBIN "gfx/sprites/trunks.2bpp"
SittingYoungsterGFX::          INCBIN "gfx/sprites/sitting_youngster.2bpp"
SittingBirdKeeperGFX::         INCBIN "gfx/sprites/sitting_birdkeeper.2bpp"
SittingGuyGFX::                INCBIN "gfx/sprites/sitting_guy.2bpp"
SittingGentlemanGFX::          INCBIN "gfx/sprites/sitting_gentleman.2bpp"
SittingTwinGFX::               INCBIN "gfx/sprites/sitting_twin.2bpp"
SittingPonytailGFX::           INCBIN "gfx/sprites/sitting_ponytail.2bpp"
SittingPokeFanGFX::            INCBIN "gfx/sprites/sitting_pokefan.2bpp"
SittingLadyGFX::               INCBIN "gfx/sprites/sitting_lady.2bpp"
MallSignGFX::              	   INCBIN "gfx/sprites/mall_sign.2bpp"
CampfireGFX::              	   INCBIN "gfx/sprites/campfire.2bpp"
Valve1GFX::					   INCBIN "gfx/sprites/valve1.2bpp"
Valve2GFX::					   INCBIN "gfx/sprites/valve2.2bpp"
PlankBridgeGFX::			   INCBIN "gfx/sprites/plankbridge.2bpp"
PlankBridge2GFX::			   INCBIN "gfx/sprites/plankbridge2.2bpp"
TrafficLightGFX::			   INCBIN "gfx/sprites/traffic_light.2bpp"
HangarPartsGFX::			   INCBIN "gfx/sprites/hangar_parts.2bpp"
KoffingBeanGFX::			   INCBIN "gfx/sprites/koffing_bean.2bpp"
ClothesRacksGFX::			   INCBIN "gfx/sprites/clothes_racks.2bpp"
IceBlockGFX::			  	   INCBIN "gfx/sprites/ice_block.2bpp"
BigMamoswineSpriteGFX::        INCBIN "gfx/sprites/big_mamoswine.2bpp"
LighthouseSpriteGFX::      	   INCBIN "gfx/sprites/lighthouse.2bpp"
FrankieSpriteGFX::             INCBIN "gfx/sprites/frankie.2bpp"
SkaterSpriteGFX::              INCBIN "gfx/sprites/skater.2bpp"
SpaWorkerSpriteGFX::           INCBIN "gfx/sprites/spa_worker.2bpp"
SpaTrainerSpriteGFX::          INCBIN "gfx/sprites/spa_trainer.2bpp"


SECTION "Overworld Sprites 8", ROMX

RedSpriteGFX::           	   INCBIN "gfx/sprites/red.2bpp"
RedBikeSpriteGFX::       	   INCBIN "gfx/sprites/red_bike.2bpp"
RedSurfSpriteGFX::       	   INCBIN "gfx/sprites/red_surf.2bpp"
RedRunSpriteGFX::              INCBIN "gfx/sprites/red_run.2bpp"
RedMiscSpriteGFX::             INCBIN "gfx/sprites/red_misc.2bpp"
LeafSpriteGFX::                INCBIN "gfx/sprites/pippi.2bpp"
LeafBikeSpriteGFX::            INCBIN "gfx/sprites/pippi_bike.2bpp"
LeafSurfSpriteGFX::            INCBIN "gfx/sprites/cora_surf.2bpp"
LeafRunSpriteGFX::             INCBIN "gfx/sprites/pippi_run.2bpp"
LeafMiscSpriteGFX::            INCBIN "gfx/sprites/pippi_misc.2bpp"
GoldSpriteGFX::                INCBIN "gfx/sprites/pippi.2bpp"
GoldBikeSpriteGFX::            INCBIN "gfx/sprites/pippi_bike.2bpp"
GoldSurfSpriteGFX::            INCBIN "gfx/sprites/cora_surf.2bpp"
GoldRunSpriteGFX::             INCBIN "gfx/sprites/pippi_run.2bpp"
GoldMiscSpriteGFX::            INCBIN "gfx/sprites/pippi_misc.2bpp"
KrisSpriteGFX::                INCBIN "gfx/sprites/pippi.2bpp"
KrisBikeSpriteGFX::            INCBIN "gfx/sprites/pippi_bike.2bpp"
KrisSurfSpriteGFX::            INCBIN "gfx/sprites/cora_surf.2bpp"
KrisRunSpriteGFX::             INCBIN "gfx/sprites/pippi_run.2bpp"
KrisMiscSpriteGFX::            INCBIN "gfx/sprites/pippi_misc.2bpp"
CorySkateboardSpriteGFX::	   INCBIN "gfx/sprites/cory_skateboard.2bpp"
CoraSkateboardSpriteGFX::	   INCBIN "gfx/sprites/cora_skateboard.2bpp"
PippiSkateboardSpriteGFX::	   INCBIN "gfx/sprites/pippi_skateboard.2bpp"
RedSkateboardSpriteGFX::	   INCBIN "gfx/sprites/red_skateboard.2bpp"
LeafSkateboardSpriteGFX::	   INCBIN "gfx/sprites/leaf_skateboard.2bpp"
GoldSkateboardSpriteGFX::	   INCBIN "gfx/sprites/gold_skateboard.2bpp"
KrisSkateboardSpriteGFX::	   INCBIN "gfx/sprites/kris_skateboard.2bpp"
CorySkateboard2SpriteGFX::	   INCBIN "gfx/sprites/cory_skateboard_2.2bpp"
CoraSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/cora_skateboard_2.2bpp"
PippiSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/pippi_skateboard_2.2bpp"
RedSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/red_skateboard_2.2bpp"
LeafSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/leaf_skateboard_2.2bpp"
GoldSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/gold_skateboard_2.2bpp"
KrisSkateboard2SpriteGFX::	   INCBIN "gfx/sprites/kris_skateboard_2.2bpp"

SECTION "Overworld Sprites 9", ROMX

CorySkateboardGrindingSpriteGFX::	   INCBIN "gfx/sprites/cory_skateboard_grinding.2bpp"
CorySkateboardFallingSpriteGFX::	   INCBIN "gfx/sprites/cory_skateboard_falling.2bpp"
CoraSkateboardGrindingSpriteGFX::	   INCBIN "gfx/sprites/cora_skateboard_grinding.2bpp"
CoraSkateboardFallingSpriteGFX::	   INCBIN "gfx/sprites/cora_skateboard_falling.2bpp"
PippiSkateboardGrindingSpriteGFX::	   INCBIN "gfx/sprites/pippi_skateboard_grinding.2bpp"
RedSkateboardGrindingSpriteGFX::	   INCBIN "gfx/sprites/red_skateboard_grinding.2bpp"
LeafSkateboardGrindingSpriteGFX::	   INCBIN "gfx/sprites/leaf_skateboard_grinding.2bpp"
GoldSkateboardGrindingSpriteGFX::	   INCBIN "gfx/sprites/gold_skateboard_grinding.2bpp"
KrisSkateboardGrindingSpriteGFX::	   INCBIN "gfx/sprites/kris_skateboard_grinding.2bpp"